-- Appliance - Module 2: Tools, Meters and Safe Testing
-- Paste the WHOLE file, press Run. Safe to re-run.

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2);
DELETE FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '84d4df93-67e6-448c-8c01-6538b9dddad4', 'Module 2: Tools, Meters and Safe Testing', 'Twenty questions on Tools, Meters and Safe Testing.', 70, 30, 'module', 'beginner', 2);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'Before opening the casing of any mains appliance to test inside it, what must you do first?', 'multiple_choice', '{"A": "Unplug it from the wall socket, or switch off and lock off the circuit if it is hard-wired", "B": "Switch the appliance off at its own on/off button", "C": "Set your multimeter to the AC volts range", "D": "Put on cotton gloves"}'::jsonb, 'A', 'The appliance''s own switch may only break one pole and leaves parts live inside. Full isolation means removing the plug or locking off the supply so nobody can re-energise it while your hands are inside.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), '''Proving dead'' correctly means you:', 'multiple_choice', '{"A": "Prove your tester works on a known live source, test the circuit is dead, then prove the tester still works", "B": "Look for indicator lamps to be off", "C": "Test the circuit, then put the meter away", "D": "Touch the terminal briefly with the back of your hand"}'::jsonb, 'A', 'A tester with a flat battery or broken lead reads zero volts on a live circuit. Proving it before and after on a known source is the only way to trust the dead reading.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'Your multimeter is set to the resistance (ohms) range and you connect it across a circuit that is still live at 230 V. What is the likely result?', 'multiple_choice', '{"A": "It reads the resistance normally", "B": "Nothing happens because ohms mode ignores voltage", "C": "The meter reads infinity and stays safe", "D": "The meter''s internal fuse blows, or the meter is damaged, and there is a flash risk"}'::jsonb, 'D', 'Resistance mode applies the meter''s own small voltage and expects no external supply. Mains applied to that range destroys the meter and can cause an arc, so always isolate and prove dead before any ohms test.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'A customer''s appliance must be tested with the power on because the fault only appears when running. What is the correct approach for a small repair business?', 'multiple_choice', '{"A": "Work live with one hand behind your back to be safe", "B": "Ask the customer to hold the appliance steady while you probe", "C": "Live testing is always fine as long as the floor is dry", "D": "Avoid live working; use symptom questioning, dead tests and safe substitution, and if a live measurement is genuinely unavoidable use proper insulated probes, a fused test lead set and a barrier so nothing can be touched"}'::jsonb, 'D', 'Live working is a last resort, never routine. Almost every appliance fault can be found dead with resistance and continuity tests, and live measurement demands proper equipment and controlled access.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'For general appliance work on a 230 V supply, the minimum safe category rating for a multimeter and its leads is:', 'multiple_choice', '{"A": "CAT II 600 V or better, with the leads matching the meter''s rating", "B": "Any meter sold in the market, since they all read the same", "C": "CAT I 100 V is sufficient for appliances", "D": "The category only matters for meters used outdoors"}'::jsonb, 'A', 'CAT ratings describe how much transient energy the meter can survive without exploding. Appliance and socket-outlet work sits in CAT II, and cheap unrated leads are often the weakest link even on a good meter.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'You measure continuity through a heating element and the meter reads ''OL'' or ''1'' on the left of the display. This means:', 'multiple_choice', '{"A": "The element is a dead short", "B": "The element is fine", "C": "The meter batteries are flat", "D": "The resistance is above the meter''s range, effectively an open circuit, so the element is broken"}'::jsonb, 'D', 'OL means over-limit: no measurable path. For an element that should read a few tens or hundreds of ohms, OL confirms the resistance wire has burned open and the element must be replaced.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'Before taking any resistance reading, why should you touch the two meter probes together?', 'multiple_choice', '{"A": "To check the leads and meter read near zero, so you know lead resistance and a broken lead are not fooling you", "B": "To charge the meter''s capacitor", "C": "To discharge static from your body", "D": "To reset the meter to factory settings"}'::jsonb, 'A', 'A cracked lead reads open on everything and would make every good component look faulty. Shorting the probes first shows the leads are sound and reveals their own small resistance.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'What does an insulation resistance tester (megger) do that a normal multimeter cannot?', 'multiple_choice', '{"A": "It applies a high test voltage such as 500 V DC to reveal insulation that leaks only under mains-level stress", "B": "It reads AC voltage more accurately", "C": "It measures current without breaking the circuit", "D": "It measures the frequency of the supply"}'::jsonb, 'A', 'Damp or damaged insulation can read fine at the multimeter''s couple of volts but break down at 230 V. Only a high-voltage insulation test exposes that hidden leakage between live parts and earth.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'Which of these is NOT a safe substitute for a proper insulated screwdriver when working inside appliances?', 'multiple_choice', '{"A": "A VDE-marked insulated screwdriver", "B": "A screwdriver with a factory-moulded insulated shaft", "C": "A bare metal screwdriver with electrical tape wrapped around the shaft", "D": "An insulated screwdriver with an undamaged sleeve"}'::jsonb, 'C', 'Tape peels, absorbs moisture and is not tested to withstand mains voltage. Only manufactured, tested insulation can be trusted near circuits, and even then you isolate first.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'Where should the ammeter function of a clamp meter be placed to measure the current an appliance is drawing?', 'multiple_choice', '{"A": "Around the whole flexible cord containing live and neutral", "B": "Around the earth wire", "C": "Across the two pins of the plug", "D": "Around a single conductor only, such as the live core inside the appliance or one leg of a split adaptor lead"}'::jsonb, 'D', 'Live and neutral currents are equal and opposite, so clamping the whole cord gives almost zero. The clamp must see one conductor alone to read load current.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'A clamp meter placed around the whole flex of a working appliance reads 12 mA instead of zero. What does this suggest?', 'multiple_choice', '{"A": "The appliance is drawing 12 mA in total, so it is very efficient", "B": "The clamp is faulty", "C": "Normal capacitive behaviour that can be ignored", "D": "Current is returning by another path, meaning earth leakage that will trip an RCD and may indicate dangerous insulation failure"}'::jsonb, 'D', 'Any imbalance between live and neutral is current leaving through earth or a person. Twelve milliamps is well above the level that trips a 30 mA RCD in practice and is a real shock risk.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'When soldering a joint inside an appliance, which practice gives the most reliable long-term repair?', 'multiple_choice', '{"A": "Twist the wires, apply plenty of flux paste meant for plumbing, and cover with tape", "B": "Clean the conductors, make a mechanically sound joint, use electronics-grade rosin-cored solder, and insulate with heat-shrink", "C": "Solder the wires while the board is still connected to the mains", "D": "Use as much solder as possible so the joint is thick"}'::jsonb, 'B', 'Acid plumbing flux corrodes copper over months and tape unwinds in heat. A clean, mechanically supported joint with rosin-cored solder and heat-shrink survives vibration and humidity.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'A ''non-contact voltage detector'' pen glows near a wire. What is the correct conclusion?', 'multiple_choice', '{"A": "The wire is definitely live and it is safe to rely on the pen alone", "B": "The wire is definitely dead", "C": "It suggests voltage may be present, but it can also give false positives and false negatives, so a dead state must still be proved with a two-pole tester or meter", "D": "The neutral is disconnected"}'::jsonb, 'C', 'These pens sense electric fields and are fooled by induced voltage, screening and battery condition. They are useful for a first warning but never acceptable proof that something is dead.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'You need to replace a blown fuse in a plug on an appliance rated 500 W at 230 V. Which fuse is appropriate?', 'multiple_choice', '{"A": "The largest fuse that fits, so it does not blow again", "B": "A fuse rated just above the appliance''s normal current and suitable for the flex, such as a 3 A cartridge fuse", "C": "A short piece of copper wire", "D": "A 13 A fuse in every case"}'::jsonb, 'B', 'At 230 V a 500 W load draws roughly 2.2 A, so a 3 A fuse protects the flex. Oversized fuses or wire bridges let a faulty flex overheat and start a fire instead of disconnecting.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'A customer asks you to bypass a repeatedly blowing fuse or a thermal cut-out to save money. The correct response is:', 'multiple_choice', '{"A": "Bypass it but warn the customer verbally", "B": "Bypass it only if the appliance is old", "C": "Refuse, explain that the device is protecting against a real fault, and find and fix the underlying cause", "D": "Fit a higher-rated fuse as a compromise"}'::jsonb, 'C', 'A protective device that keeps operating is reporting a fault, not causing one. Defeating it converts a nuisance into a fire or shock hazard and destroys your liability position as a business.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'Which meter setting is used to check whether a switch closes properly?', 'multiple_choice', '{"A": "AC volts, with the appliance plugged in", "B": "Continuity or low ohms, with the appliance isolated and the switch removed from parallel paths", "C": "DC current", "D": "Capacitance"}'::jsonb, 'B', 'A good switch reads near zero ohms closed and open circuit when off. The appliance must be isolated, and other components in parallel can give misleading low readings unless one side is disconnected.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'What is the main safety purpose of a rubber or insulating mat on the workshop floor at the test bench?', 'multiple_choice', '{"A": "To keep the appliance from sliding", "B": "To stop dust entering the appliance", "C": "To reduce the chance of a fatal current path from hand to feet through earth by insulating you from the concrete floor", "D": "To improve the earth connection"}'::jsonb, 'C', 'Bare or damp concrete is a good conductor to earth, so a hand-to-foot shock passes through the chest. An insulating mat raises the resistance of that path considerably.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'You are testing an appliance on the bench and the supply keeps tripping the workshop RCD. The best practice is:', 'multiple_choice', '{"A": "Plug the appliance into a socket that has no RCD so you can keep working", "B": "Treat the trip as a genuine fault indication and investigate insulation and earth leakage before powering up again", "C": "Hold the RCD test button in while running the appliance", "D": "Reset the RCD repeatedly until it holds"}'::jsonb, 'B', 'The RCD is telling you current is escaping to earth, which is exactly the condition that electrocutes people. Defeating it removes your own protection and the customer''s.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'After any repair on a mains appliance, which check should be done before returning it to the customer?', 'multiple_choice', '{"A": "Only a visual check that the screws are back in", "B": "Only that the appliance switches on", "C": "An earth continuity check from the plug earth pin to exposed metal (on Class I appliances), an insulation check, and confirmation that no wire can touch hot or moving parts", "D": "Only a test of the thermostat"}'::jsonb, 'C', 'A repair is not finished until the appliance is proved electrically safe. Earth continuity and insulation are the two tests that catch the faults that shock or kill users.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2), 'Working with limited equipment, which single tool combination gives the best safety value for a small appliance repair business?', 'multiple_choice', '{"A": "A cheap unbranded pocket multimeter and a screwdriver set", "B": "A CAT-rated multimeter with fused leads, a two-pole voltage tester for proving dead, and insulated hand tools", "C": "A non-contact pen and a set of pliers", "D": "A clamp meter alone"}'::jsonb, 'B', 'Those three cover isolation, proving dead and safe dead testing, which is where almost all electrical accidents are prevented. Extra instruments are useful but do not replace this core.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=2);
-- expect 20
