-- Appliance - Module 3: Electrical Fundamentals for Repairers
-- Paste the WHOLE file, press Run. Safe to re-run.

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3);
DELETE FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '84d4df93-67e6-448c-8c01-6538b9dddad4', 'Module 3: Electrical Fundamentals for Repairers', 'Twenty questions on Electrical Fundamentals for Repairers.', 70, 30, 'module', 'beginner', 3);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'On a 230 V 50 Hz single-phase supply, what do the terms live, neutral and earth describe?', 'multiple_choice', '{"A": "Live carries the supply voltage, neutral is the return conductor near earth potential, and earth is a protective conductor that carries fault current safely away", "B": "Live and neutral are interchangeable, and earth carries the working current", "C": "Live is positive, neutral is negative and earth is the middle voltage", "D": "All three carry equal current in normal operation"}'::jsonb, 'A', 'Neutral is bonded to earth at the supply, so it sits near zero volts, while live swings to mains potential. Earth carries no current normally and exists only to make a fault blow the fuse or trip the RCD.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'An appliance element is marked 2000 W at 230 V. Roughly what current does it draw?', 'multiple_choice', '{"A": "About 0.12 A", "B": "About 46 A", "C": "About 8.7 A", "D": "About 20 A"}'::jsonb, 'C', 'Current equals power divided by voltage, so 2000 divided by 230 is about 8.7 A. Knowing this lets you choose the right fuse, flex and clamp-meter expectation.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'Using Ohm''s law, what resistance would that 2000 W, 230 V element have when hot?', 'multiple_choice', '{"A": "About 8.7 ohms", "B": "About 26 ohms", "C": "About 230 ohms", "D": "About 2000 ohms"}'::jsonb, 'B', 'Resistance equals voltage divided by current, so 230 divided by 8.7 is roughly 26 ohms. A cold reading close to this confirms the element is intact, while OL means it is open.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'Why is the earth conductor essential on a Class I metal-bodied appliance?', 'multiple_choice', '{"A": "It reduces the electricity bill", "B": "It stops the appliance producing electrical noise", "C": "It improves motor starting torque", "D": "If a live wire touches the metal body, the earth gives a low-resistance path so a large fault current flows and the protective device disconnects the supply"}'::jsonb, 'D', 'Without earth, the casing simply sits at 230 V waiting for a person to complete the circuit. With earth, the fault current is large enough to blow the fuse or trip the RCD almost instantly.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'A Class II (double insulated) appliance is identified by which marking, and what does it mean?', 'multiple_choice', '{"A": "A square inside a square symbol, meaning protection comes from two layers of insulation rather than an earth connection", "B": "A triangle symbol, meaning it must always be earthed", "C": "A circle symbol, meaning it runs on DC", "D": "A star symbol, meaning it is energy efficient"}'::jsonb, 'A', 'The double-square symbol means there is no reliance on an earth wire, so these appliances legitimately have two-core flex. Never add an earth wire to a Class II appliance''s plastic body or assume a missing earth is a fault.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'What is the practical difference between a series and a parallel connection inside an appliance?', 'multiple_choice', '{"A": "Series connections always carry more current than parallel ones", "B": "In series the same current passes through each component and a break anywhere stops everything; in parallel each branch has the full supply voltage and one branch can fail while others work", "C": "Parallel connections are used only in DC circuits", "D": "Series circuits share voltage equally regardless of resistance"}'::jsonb, 'B', 'Understanding this tells you what a symptom means: if everything is dead, suspect a common series item such as a switch, fuse or thermal cut-out. If one function fails alone, suspect that parallel branch.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'A thermostat, a door switch and a heating element are wired in series. The appliance is completely dead. What is the most efficient first diagnostic step?', 'multiple_choice', '{"A": "Replace the element immediately", "B": "Replace the thermostat immediately", "C": "Run the appliance live and feel for heat", "D": "With the appliance isolated and proved dead, check continuity across each component in turn to find the open one"}'::jsonb, 'D', 'In a series string only one open component is needed to kill the circuit, and dead continuity tests find it in minutes. Replacing parts by guesswork wastes the customer''s money and your reputation.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'What does an RCD (residual current device, also called earth leakage) actually detect?', 'multiple_choice', '{"A": "Excess total current drawn by the load", "B": "High voltage on the supply", "C": "A difference between the current flowing out in the live conductor and returning in the neutral, indicating current leaking to earth or through a person", "D": "Short circuits between live and neutral only"}'::jsonb, 'C', 'An RCD compares live and neutral currents and trips when they differ, typically at 30 mA for personal protection. It does not detect overload, which is the job of the fuse or circuit breaker.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'A 30 mA RCD protects people mainly because:', 'multiple_choice', '{"A": "It disconnects quickly at a leakage current below the level that normally causes fatal ventricular fibrillation in a healthy adult", "B": "It limits the voltage on the appliance to 30 V", "C": "It prevents any shock from being felt at all", "D": "It replaces the need for an earth conductor entirely"}'::jsonb, 'A', 'A 30 mA RCD still lets you feel a painful shock, but it cuts the supply fast enough that the current usually does not stop the heart. It reduces the severity of a shock; it does not prevent one.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'A customer complains their RCD trips only when the water heater runs. What is the most likely cause?', 'multiple_choice', '{"A": "The RCD is too sensitive and should be replaced with a 100 mA type", "B": "The supply voltage is too high", "C": "The appliance is drawing too much power for the circuit", "D": "Moisture or a failing element is allowing current to leak from the live circuit to earth inside the heater"}'::jsonb, 'D', 'Water heater elements commonly fail by letting mains leak through cracked sheathing into the water and earth. An insulation resistance test between element terminals and earth confirms it, and the element must be replaced.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'Why does a loose connection in a terminal or plug get hot?', 'multiple_choice', '{"A": "Because loose wires carry more current than tight ones", "B": "Because the voltage rises at the loose point", "C": "Because the poor contact adds resistance, and power dissipated at that point rises with current squared times that resistance", "D": "Because the earth wire draws current through the loose joint"}'::jsonb, 'C', 'Even a small added resistance dissipates real power at high current, which chars insulation and eventually causes fire. Discoloured, brittle or smelly terminals should always be remade or replaced, not just retightened.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'What does a low insulation resistance reading, for example 0.05 megohm between live and earth, tell you?', 'multiple_choice', '{"A": "The appliance is well insulated", "B": "Insulation has broken down or is damp, so leakage current will flow to earth and the appliance is unsafe to return to the customer", "C": "The earth wire is disconnected", "D": "The reading is normal for heating appliances"}'::jsonb, 'B', 'Healthy appliance insulation reads in the megohms, typically well above 1 megohm. A fraction of a megohm means significant leakage, an RCD that will trip and a genuine shock risk.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'Which statement about voltage drop on a long extension lead is correct?', 'multiple_choice', '{"A": "A long thin lead drops voltage under load, so a motor at the far end sees less than 230 V, runs hotter and may fail to start", "B": "Extension leads have no effect because voltage is constant", "C": "A coiled lead is safer under heavy load than an uncoiled one", "D": "Voltage drop only matters on DC circuits"}'::jsonb, 'A', 'Cable resistance times current is voltage lost before the appliance, and undervoltage causes high motor current and overheating. Coiled leads make it worse by trapping heat, so always uncoil fully under load.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'On a 50 Hz supply, what determines the running speed of a simple induction motor?', 'multiple_choice', '{"A": "The applied voltage alone", "B": "The length of the supply cable", "C": "The supply frequency and the number of poles in the motor, less a small amount of slip under load", "D": "The size of the run capacitor"}'::jsonb, 'C', 'Synchronous speed is set by frequency and pole count, so a 2-pole motor on 50 Hz runs near 3000 rpm and a 4-pole near 1500 rpm. Voltage affects torque and heating, not the basic speed.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'Why must you never rely on neutral as a substitute for earth, for example by bonding an appliance casing to neutral?', 'multiple_choice', '{"A": "Because neutral carries a higher voltage than earth", "B": "Because it would reduce the appliance''s efficiency", "C": "Because it makes the RCD more sensitive", "D": "Because if the neutral connection breaks or the plug is reversed, the entire casing becomes live at mains potential"}'::jsonb, 'D', 'Neutral carries load current and is not a protective conductor, so any break upstream puts the casing at full supply voltage through the load. This bodge has killed people and must never be used.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'How should you measure supply voltage at a socket safely?', 'multiple_choice', '{"A": "Insert bare wires and touch them with the probes", "B": "Use a CAT-rated meter or two-pole tester with properly shrouded probes, keeping fingers behind the finger guards and testing live-neutral, live-earth and neutral-earth", "C": "Use the resistance range across the socket", "D": "Use a non-contact pen and record the reading it shows"}'::jsonb, 'B', 'The three readings together reveal a lost neutral, a missing earth or reversed polarity. Shrouded probes and finger guards keep you from bridging contacts or touching a live tip.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'At a socket you measure live-neutral 230 V, live-earth 230 V and neutral-earth 0 V. What does this indicate?', 'multiple_choice', '{"A": "The earth is disconnected", "B": "Live and neutral are reversed", "C": "The supply appears normal for a system where neutral and earth are bonded at the supply", "D": "There is a dangerous voltage on the earth conductor"}'::jsonb, 'C', 'Because neutral is referenced to earth at the source, live measures the same to both, and neutral to earth is near zero. A significant neutral-earth voltage instead suggests a heavily loaded or failing neutral.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'A capacitor in an appliance can hold a dangerous charge after the power is removed. What is the correct action before touching its terminals?', 'multiple_choice', '{"A": "Discharge it deliberately through a suitable resistor across the terminals, then confirm with a meter that the voltage has fallen to near zero", "B": "Short it directly with a screwdriver blade as standard practice", "C": "Wait ten seconds; all capacitors self-discharge in that time", "D": "Touch one terminal only, since one terminal cannot shock you"}'::jsonb, 'A', 'A charged motor-run or power-supply capacitor can deliver a painful or damaging shock long after unplugging. A resistor discharges it without the violent arc, pitting and shrapnel risk of a direct screwdriver short, and the meter proves it worked.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'What is the difference between a fuse or circuit breaker and an RCD in terms of protection?', 'multiple_choice', '{"A": "They do the same job and either one alone is enough", "B": "The fuse or breaker protects the cable and appliance against overload and short circuit, while the RCD protects people against earth leakage and shock", "C": "The RCD protects the cable while the fuse protects people", "D": "Only the RCD protects against short circuits"}'::jsonb, 'B', 'Overcurrent devices react to too much current in the circuit; an RCD reacts to current going where it should not. A workshop needs both, and neither substitutes for the other.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3), 'A customer''s mains voltage sags badly and their fridge compressor keeps failing to start. Which explanation and advice is technically sound?', 'multiple_choice', '{"A": "Low voltage cannot harm motors, so the compressor is simply old", "B": "The compressor should be rewired for a lower voltage", "C": "Fitting a larger fuse will help the compressor start", "D": "At low voltage the motor cannot develop starting torque, so it stalls and draws locked-rotor current until the overload trips; repeated stalling overheats the windings, and a voltage stabiliser or supply fix is the real remedy"}'::jsonb, 'D', 'A stalled compressor draws several times its running current with no cooling airflow through the windings. Repeated cycling like this is a common cause of burnt-out compressors on weak supplies.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='84d4df93-67e6-448c-8c01-6538b9dddad4' AND quiz_sequence=3);
-- expect 20
