-- Bakery - Module 4: Baking, Ovens and Heat Control
-- Paste the WHOLE file, press Run. Safe to re-run.

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4);
DELETE FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '3bcc47e7-883e-48e2-96dc-ee41bad53e48', 'Module 4: Baking, Ovens and Heat Control', 'Twenty questions on Baking, Ovens and Heat Control.', 70, 30, 'module', 'intermediate', 4);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'What is ''oven spring''?', 'multiple_choice', '{"A": "The metal shelf support inside the oven", "B": "The rapid rise of the loaf in the first minutes of baking", "C": "The cooling contraction after baking", "D": "The steam vent on a commercial oven"}'::jsonb, 'B', 'Heat makes trapped gas expand, water turn to steam and yeast work fast before dying, all of which lift the loaf sharply early in the bake. Once the crust sets, the loaf can no longer expand.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Roughly what internal temperature indicates a lean crusty loaf is baked through?', 'multiple_choice', '{"A": "About 60 °C (140 °F)", "B": "About 75 °C (167 °F)", "C": "About 96–99 °C (205–210 °F)", "D": "About 120 °C (248 °F)"}'::jsonb, 'C', 'A lean loaf is done when the centre reaches roughly 96–99 °C (205–210 °F), by which point starch is gelatinised and the crumb is set. Soft enriched loaves are usually taken a little lower, around 88–93 °C (190–200 °F).', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why is steam useful in the first part of baking a crusty loaf?', 'multiple_choice', '{"A": "It keeps the crust soft and moist so the loaf can expand fully before the crust sets", "B": "It makes the yeast live longer through the whole bake", "C": "It prevents the bread from cooking inside", "D": "It replaces the need for scoring"}'::jsonb, 'A', 'Moisture delays crust formation so the loaf gets maximum oven spring, and it later helps gelatinise the surface starch for a glossy crisp crust. Without steam the crust sets early and restricts the rise.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'A practical low-cost way to create steam in a small domestic oven is to:', 'multiple_choice', '{"A": "Spray the heating element directly with water", "B": "Leave the oven door open during baking", "C": "Place a tray of hot water or a preheated pan with hot water on the oven floor", "D": "Add water directly into the dough tin"}'::jsonb, 'C', 'A preheated pan filled with hot water at loading time releases steam quickly and safely. Never spray elements or glass directly, as thermal shock can crack glass or damage the element.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why do bakers score (slash) the top of a loaf before baking?', 'multiple_choice', '{"A": "Purely for decoration with no functional effect", "B": "To let the loaf expand in a controlled direction instead of bursting at a weak point", "C": "To let steam escape so the loaf stays flat", "D": "To reduce the baking time by half"}'::jsonb, 'B', 'A slash gives the expanding loaf a planned weak point so it opens neatly instead of tearing at the side. It gives control over the finished shape as well as an attractive ear.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Which browning reaction, between proteins and sugars, gives crust its colour and flavour?', 'multiple_choice', '{"A": "Fermentation", "B": "Gelatinisation", "C": "Saponification", "D": "The Maillard reaction"}'::jsonb, 'D', 'The Maillard reaction between amino acids and reducing sugars produces the brown colour and the roasted aromas of crust. Caramelisation of sugars contributes as well, especially in sweet doughs.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why do enriched, sugary doughs such as buns usually bake at a lower temperature than a lean crusty loaf?', 'multiple_choice', '{"A": "Because they contain no yeast", "B": "Because the sugar and milk solids brown fast and can burn before the centre is cooked", "C": "Because they contain more water", "D": "Because they need no oven spring"}'::jsonb, 'B', 'Sugar, milk and egg all accelerate browning, so a hot oven darkens the outside long before the middle is set. A moderate oven lets the heat reach the centre evenly.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'When baking on a wood-fired oven, what does a bright white or clear oven interior after firing usually indicate?', 'multiple_choice', '{"A": "The oven is too cold to bake", "B": "The soot has burned off, showing the oven has reached a high baking heat", "C": "The oven is full of smoke", "D": "The bricks are cracked"}'::jsonb, 'B', 'Soot deposited on the dome burns off once the oven reaches high heat, leaving the surface clear. Bakers use this as a simple visual sign that the oven is up to temperature.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'In a wood-fired or retained-heat oven, in what order are products normally baked?', 'multiple_choice', '{"A": "Anything, in any order, since temperature never changes", "B": "Slow-dried biscuits first, then bread", "C": "Hottest items first, such as bread, then lower-temperature items as the oven cools", "D": "Only one item per firing"}'::jsonb, 'C', 'A retained-heat oven cools steadily after the fire is removed, so bakers work down the temperature scale. Bread goes in first, then buns and cakes, then anything needing gentle drying heat.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'An oven with a fan (convection) compared with a static oven at the same dial setting will generally:', 'multiple_choice', '{"A": "Bake more slowly and less evenly", "B": "Have no effect on baking at all", "C": "Bake faster and more evenly, so the temperature is often reduced by about 20 °C (36 °F)", "D": "Only work for cakes"}'::jsonb, 'C', 'Moving air transfers heat faster and evens out hot spots, so goods bake quicker and can dry out if the setting is not reduced. A common adjustment is about 20 °C (36 °F) lower than a static recipe.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Your gas oven browns loaves heavily on one side and leaves the other pale. What is the most practical response?', 'multiple_choice', '{"A": "Buy a new oven immediately", "B": "Rotate the trays part-way through the bake and learn the oven''s hot spots", "C": "Bake at a much lower temperature for twice as long", "D": "Stop using that oven for bread"}'::jsonb, 'B', 'Almost every small oven has hot and cool zones, and turning the trays evens out the colour. Mapping your own oven is one of the cheapest quality improvements a small bakery can make.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why should an oven be preheated properly before loading bread?', 'multiple_choice', '{"A": "To dry out the oven shelves", "B": "So that yeast keeps working through the whole bake", "C": "Because a cold or rising oven gives poor oven spring, pale crust and a dense crumb", "D": "Because bread cannot be baked in a hot oven"}'::jsonb, 'C', 'Bread relies on a burst of high heat at the start to expand before the crust sets. Loading into a rising oven lets the dough dry and slump instead of springing.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why is a separate oven thermometer worth having even if the oven has a dial?', 'multiple_choice', '{"A": "Dials often read differently from the real temperature, especially on older or cheaper ovens", "B": "Thermometers make bread rise faster", "C": "It is a legal requirement everywhere", "D": "It replaces the need to preheat"}'::jsonb, 'A', 'Thermostats drift and dials are often marked inaccurately, so the real oven temperature can be well off the setting. A cheap oven thermometer tells you what is actually happening.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why should bread be cooled on a wire rack rather than left in the tin or flat on a solid surface?', 'multiple_choice', '{"A": "It keeps the bread warmer for longer", "B": "Air circulating underneath lets steam escape and prevents a soggy base", "C": "It stops the crust forming", "D": "It makes the loaf rise further"}'::jsonb, 'B', 'Steam trapped under a hot loaf condenses and softens the bottom crust into a damp, gummy layer. A rack lets moisture escape from all sides.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why is it better to let a loaf cool substantially before slicing?', 'multiple_choice', '{"A": "Because it is still fermenting", "B": "Because it is hot enough to burn all customers", "C": "Because the crumb is still setting and slicing hot bread gives a gummy, squashed texture", "D": "Because slicing hot bread makes it go mouldy immediately"}'::jsonb, 'C', 'Starch continues to set and excess moisture keeps evaporating as the loaf cools, so an early cut compresses a still-soft crumb. Cooling gives clean slices and better texture.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'What does baking loss (bake-out loss) refer to?', 'multiple_choice', '{"A": "Dough dropped on the floor during shaping", "B": "The weight of water lost as steam during baking, so the baked loaf weighs less than the dough", "C": "Money lost when bread does not sell", "D": "The gas lost when dough is knocked back"}'::jsonb, 'B', 'A loaf leaves the oven lighter than the dough that went in because water evaporates during baking. Bakers allow for this when scaling dough to hit a target finished loaf weight.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'To sell loaves at a finished weight of about 500 g (about 1 lb 2 oz), a baker should scale the dough pieces:', 'multiple_choice', '{"A": "At exactly 500 g", "B": "Well below 500 g", "C": "Somewhat above 500 g to allow for water lost in baking", "D": "At double the finished weight"}'::jsonb, 'C', 'Because water evaporates in the oven, the dough must be scaled heavier than the target finished weight. The exact allowance is found by weighing your own cooled loaves and adjusting.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'A loaf is dark on the outside but doughy and wet in the middle. What is the most likely cause?', 'multiple_choice', '{"A": "The oven was too hot, so the outside set and coloured before the centre cooked", "B": "There was too much salt", "C": "The dough was under-proved only", "D": "The flour was too strong"}'::jsonb, 'A', 'Excess heat drives colour and crust formation far faster than heat can penetrate to the centre. Lower the temperature and extend the bake, and check with a thermometer.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Why should trays not be packed tightly together on every shelf of a small oven?', 'multiple_choice', '{"A": "The oven will use less electricity", "B": "Crowding blocks heat and air movement, giving uneven baking and pale patches", "C": "The trays will melt", "D": "It makes no difference in a small oven"}'::jsonb, 'B', 'Heat needs to circulate around each item, and a packed oven creates cold shadows and long bake times. Leaving gaps between trays and around the walls gives far more even results.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4), 'Which safety practice matters most when working with a hot wood or gas oven in a small home bakery?', 'multiple_choice', '{"A": "Keep a bucket of water beside the oven for fat fires", "B": "Wear loose synthetic sleeves for comfort", "C": "Use dry heatproof gloves and long-handled tools, keep the area clear, and ensure good ventilation", "D": "Bake with the door propped open to reduce the heat"}'::jsonb, 'C', 'Damp cloths conduct heat and cause steam burns, and clutter around a hot oven causes trips and spills. Good ventilation also matters because fuel-burning ovens release carbon monoxide.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=4);
-- expect 20
