-- Bakery - Module 2: Yeast, Fermentation and Proving
-- Paste the WHOLE file, press Run. Safe to re-run.

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2);
DELETE FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '3bcc47e7-883e-48e2-96dc-ee41bad53e48', 'Module 2: Yeast, Fermentation and Proving', 'Twenty questions on Yeast, Fermentation and Proving.', 70, 30, 'module', 'beginner', 2);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What gas produced by yeast is mainly responsible for making bread dough rise?', 'multiple_choice', '{"A": "Oxygen", "B": "Hydrogen", "C": "Nitrogen", "D": "Carbon dioxide"}'::jsonb, 'D', 'Yeast ferments sugars into carbon dioxide and alcohol; the carbon dioxide is trapped by the gluten network and inflates the dough. The alcohol mostly evaporates during baking.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'You have a recipe calling for 20 g of fresh (compressed) yeast but you only have instant dry yeast. Roughly how much instant dry yeast should you use?', 'multiple_choice', '{"A": "About 20 g", "B": "About 40 g", "C": "About 7 g", "D": "About 2 g"}'::jsonb, 'C', 'Instant dry yeast is used at roughly one third the weight of fresh yeast because most of the water has been removed. Using the full fresh-yeast weight would over-ferment the dough badly.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What is the main practical difference between active dry yeast and instant dry yeast?', 'multiple_choice', '{"A": "Active dry yeast is normally rehydrated in warm liquid first, while instant can be mixed straight into the flour", "B": "Instant yeast cannot be used for bread, only for cakes", "C": "Active dry yeast produces no carbon dioxide", "D": "Instant yeast must always be boiled before use"}'::jsonb, 'A', 'Active dry yeast has larger granules and a layer of dead cells, so it is usually dissolved in warm water first. Instant yeast has finer particles that hydrate quickly and can be added dry to the flour.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'At approximately what dough temperature is yeast killed outright?', 'multiple_choice', '{"A": "Around 55–60 °C (131–140 °F)", "B": "Around 40 °C (104 °F)", "C": "Around 30 °C (86 °F)", "D": "Around 100 °C (212 °F)"}'::jsonb, 'A', 'Yeast cells begin dying rapidly above roughly 55 °C (131 °F) and are dead by about 60 °C (140 °F). This is why yeast activity stops early in the bake, not at the end.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'You dissolve dry yeast in water that feels very hot to the finger, around 55 °C (131 °F). What is the likely outcome?', 'multiple_choice', '{"A": "The bread will rise faster and taste better", "B": "The yeast will be killed or badly damaged and the dough will not rise properly", "C": "Nothing changes; yeast is unaffected by water temperature", "D": "The dough will rise but taste sour"}'::jsonb, 'B', 'Water hotter than about 45 °C (113 °F) starts to damage yeast cells, and around 55 °C (131 °F) kills them. Use water that is comfortably warm, roughly 30–38 °C (86–100 °F).', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'In a hot climate where the kitchen sits around 32 °C (90 °F), what is the most sensible adjustment to a standard bread recipe?', 'multiple_choice', '{"A": "Double the yeast to keep up with the heat", "B": "Prove the dough in direct sunlight to be sure", "C": "Add extra sugar so the yeast works harder", "D": "Reduce the yeast slightly and use cooler water, and check the dough early"}'::jsonb, 'D', 'Warm surroundings already speed fermentation, so less yeast and cooler water keep the dough under control. Judging by the look and feel of the dough matters more than the clock.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What is the ''poke test'' used to judge?', 'multiple_choice', '{"A": "Whether the oven is hot enough", "B": "Whether the flour has enough protein", "C": "Whether a shaped loaf has proved enough before baking", "D": "Whether the yeast is still alive in the packet"}'::jsonb, 'C', 'A floured finger pressed lightly into the dough should leave a dent that springs back slowly and only part-way when the loaf is ready. An indent that springs back instantly means it needs longer; one that stays put means it is over-proved.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'A loaf collapses into a flat, wrinkled shape as soon as it goes into the oven. What is the most likely cause?', 'multiple_choice', '{"A": "Too little salt was used", "B": "The oven was too cold", "C": "The dough was over-proved", "D": "The flour was too strong"}'::jsonb, 'C', 'Over-proved dough has stretched its gluten to the limit and the gas cells rupture when heated, so the loaf deflates. Bake a little earlier, when the dough still has some spring.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What does salt do to yeast activity in a dough?', 'multiple_choice', '{"A": "It slows fermentation and helps control it", "B": "It speeds fermentation up sharply", "C": "It has no effect on yeast at all", "D": "It kills all the yeast instantly at any level"}'::jsonb, 'A', 'Salt draws water from yeast cells and slows their activity, giving a steadier, better-flavoured fermentation. It also strengthens gluten, which is why unsalted dough proves fast and bakes pale and slack.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'Why should salt not be tipped directly onto yeast in a dry mixing bowl and left sitting there?', 'multiple_choice', '{"A": "It makes the salt taste bitter", "B": "Direct prolonged contact with concentrated salt damages yeast cells", "C": "It causes the flour to go rancid", "D": "It stops the bread browning"}'::jsonb, 'B', 'Concentrated salt in direct contact draws moisture out of yeast cells and weakens them. Place salt and yeast on opposite sides of the flour, then mix everything together with the liquid.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What is bulk fermentation (first rise)?', 'multiple_choice', '{"A": "The rest between dividing and shaping", "B": "The cooling period after baking", "C": "The final rise of the shaped loaf", "D": "The period after mixing when the whole mass of dough ferments before dividing"}'::jsonb, 'D', 'Bulk fermentation is when the full batch of dough rises together, developing flavour, gas and gluten strength. Shaping and the final prove come afterwards.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What is the purpose of ''knocking back'' or degassing the dough after the first rise?', 'multiple_choice', '{"A": "To redistribute yeast and food, even out gas bubbles and strengthen the dough", "B": "To remove all the yeast", "C": "To cool the dough to fridge temperature", "D": "To make the dough permanently smaller"}'::jsonb, 'A', 'Degassing releases large uneven bubbles, brings yeast into contact with fresh sugars and tightens the gluten. The result is a more even crumb in the finished loaf.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'How can you test whether an old packet of dry yeast is still alive before mixing a whole batch?', 'multiple_choice', '{"A": "Smell it only", "B": "Bake a full loaf and see what happens", "C": "Stir a little into warm water with a pinch of sugar and look for foaming within about 10 minutes", "D": "Put it in the freezer overnight"}'::jsonb, 'C', 'This is called proofing the yeast: living yeast will froth and smell bready within roughly 10 minutes in warm sugared water. No foam means the yeast is dead and should be replaced.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'How should an opened sachet or tin of dry yeast be stored in a hot, humid climate?', 'multiple_choice', '{"A": "Open on the shelf beside the oven", "B": "Mixed into the flour sack", "C": "In a bowl of warm water", "D": "Sealed airtight and kept in the fridge or freezer"}'::jsonb, 'D', 'Heat and moisture both destroy dry yeast quickly, and humid air lets it absorb water and start to deteriorate. An airtight container in the fridge or freezer keeps it viable far longer.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What is a ''pre-ferment'' such as a poolish or sponge?', 'multiple_choice', '{"A": "A portion of flour, water and yeast fermented in advance and added to the final dough", "B": "The dough left over from yesterday''s baking that is thrown away", "C": "A chemical raising agent used instead of yeast", "D": "Flour that has been toasted before mixing"}'::jsonb, 'A', 'A pre-ferment matures a part of the recipe ahead of time, building acidity and flavour compounds. It gives better taste and keeping quality without needing a full sourdough culture.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'What is retarding dough?', 'multiple_choice', '{"A": "Adding extra yeast to speed the rise", "B": "Baking at a lower temperature for longer", "C": "Deliberately slowing fermentation by chilling the dough", "D": "Removing gluten from the dough"}'::jsonb, 'C', 'Chilling the dough slows yeast activity while enzymes continue developing flavour. In hot climates it is also a practical way to fit baking around a working day.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'Why does a sourdough starter rely on more than yeast alone?', 'multiple_choice', '{"A": "It contains added baking powder", "B": "It contains wild yeasts plus lactic acid bacteria that create the sour flavour", "C": "It contains no living organisms", "D": "It works only with self-raising flour"}'::jsonb, 'B', 'Lactic and acetic acid bacteria live alongside wild yeasts in a starter, producing acids that give sourdough its tang and improve keeping. The wild yeasts supply most of the lift.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'A dough smells strongly of alcohol and is very slack and sticky after being left too long in a warm room. What has happened?', 'multiple_choice', '{"A": "It has under-fermented", "B": "The salt was left out", "C": "The oven was too hot", "D": "It has over-fermented and the gluten has begun to break down"}'::jsonb, 'D', 'Prolonged fermentation builds up alcohol and acids that weaken the gluten, leaving the dough slack and hard to shape. In hot kitchens, shorten timings rather than following recipe clock times.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'Which practice best protects a proving dough from drying out and forming a skin in a breezy, warm room?', 'multiple_choice', '{"A": "Cover it with a damp cloth or sealed plastic and keep it out of direct wind and sun", "B": "Leave it uncovered in the draught", "C": "Sprinkle it with dry flour and leave it open", "D": "Place it directly under a fan"}'::jsonb, 'A', 'A dry surface crust restricts oven spring and causes cracks and tearing. Covering keeps the surface supple until baking.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2), 'Roughly what dough temperature range gives good, controllable yeast fermentation for everyday bread?', 'multiple_choice', '{"A": "5–10 °C (41–50 °F)", "B": "60–65 °C (140–149 °F)", "C": "45–50 °C (113–122 °F)", "D": "24–28 °C (75–82 °F)"}'::jsonb, 'D', 'Around 24–28 °C (75–82 °F) yeast works steadily and flavour develops well without racing ahead. Much warmer and the dough over-proves before you can shape it.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=2);
-- expect 20
