-- Bakery - Module 3: Mixing and Dough Development
-- Paste the WHOLE file, press Run. Safe to re-run.

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3);
DELETE FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '3bcc47e7-883e-48e2-96dc-ee41bad53e48', 'Module 3: Mixing and Dough Development', 'Twenty questions on Mixing and Dough Development.', 70, 30, 'module', 'beginner', 3);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Which two proteins in wheat flour combine with water to form gluten?', 'multiple_choice', '{"A": "Casein and albumin", "B": "Amylose and amylopectin", "C": "Starch and dextrin", "D": "Glutenin and gliadin"}'::jsonb, 'D', 'Glutenin gives strength and elasticity while gliadin gives extensibility, and together with water they form the gluten network. That network traps fermentation gas so the loaf rises.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Why is strong (bread) flour preferred over plain or cake flour for a yeasted loaf?', 'multiple_choice', '{"A": "It is whiter in colour", "B": "It contains more sugar", "C": "It has a higher protein content, so it forms a stronger gluten network", "D": "It absorbs less water"}'::jsonb, 'C', 'Higher protein means more gluten, which holds gas and supports a well-risen loaf. Low-protein flour makes a weak dough that spreads instead of rising.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'A recipe uses 1 000 g flour and 650 g water. What is the hydration?', 'multiple_choice', '{"A": "6.5%", "B": "35%", "C": "65%", "D": "165%"}'::jsonb, 'C', 'In baker''s percentage, water is expressed against flour weight: 650 ÷ 1 000 = 65%. Flour is always 100%, which makes recipes easy to scale up or down.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'In baker''s percentages, what does flour always represent?', 'multiple_choice', '{"A": "100%", "B": "50%", "C": "Whatever percentage is left after the other ingredients", "D": "The same percentage as the water"}'::jsonb, 'A', 'Every ingredient is expressed as a percentage of total flour weight, and flour itself is fixed at 100%. This lets you scale a formula to any batch size without recalculating ratios.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'What is the windowpane test?', 'multiple_choice', '{"A": "Holding dough to a window to check its colour", "B": "Measuring dough temperature against the window frame", "C": "Checking whether the oven glass has misted up", "D": "Stretching a small piece of dough thin enough to see light through without tearing"}'::jsonb, 'D', 'If a small piece stretches into a translucent sheet without tearing, the gluten is well developed. If it tears quickly, the dough needs more mixing or resting.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'What is autolyse?', 'multiple_choice', '{"A": "Mixing flour and water and letting them rest before adding salt and yeast", "B": "Kneading the dough continuously for an hour", "C": "Adding acid to the dough to break down gluten", "D": "Freezing the dough before shaping"}'::jsonb, 'A', 'Resting flour and water lets the flour fully hydrate and enzymes begin working, so gluten forms with much less kneading. The dough becomes smoother and more extensible.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'A dough is torn, sticky, greyish and will not hold shape after very long machine mixing. What has happened?', 'multiple_choice', '{"A": "It is under-mixed", "B": "It has too much salt", "C": "The flour was too strong", "D": "It has been over-mixed and the gluten has broken down"}'::jsonb, 'D', 'Excessive mixing, especially with heat, ruptures the gluten network beyond repair and the dough goes slack and soupy. Over-mixed dough cannot be rescued, so watch the dough rather than the timer.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Why does mixing dough by machine raise its temperature?', 'multiple_choice', '{"A": "Because friction from the hook and bowl converts mechanical energy into heat", "B": "Because yeast releases heat instantly on contact with flour", "C": "Because flour is naturally hot", "D": "Because gluten is a heat-producing chemical"}'::jsonb, 'A', 'Friction between dough, hook and bowl generates real heat, often several degrees over a mix. In hot kitchens this is why bakers use cool or iced water to hit the target dough temperature.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'In a hot kitchen your dough comes out of the mixer at 33 °C (91 °F) instead of the target 26 °C (79 °F). What is the most practical fix next batch?', 'multiple_choice', '{"A": "Add more yeast", "B": "Mix for longer", "C": "Use colder water, and mix a shorter time or in shorter bursts", "D": "Add more salt to cool the dough"}'::jsonb, 'C', 'Water temperature is the easiest variable to control, and shorter mixing adds less friction heat. Cooler dough ferments at a manageable pace and keeps its structure.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'What is the purpose of ''stretch and fold'' during bulk fermentation?', 'multiple_choice', '{"A": "To remove all gas from the dough", "B": "To stop fermentation completely", "C": "To dry the surface of the dough", "D": "To build gluten strength and even out temperature without heavy kneading"}'::jsonb, 'D', 'Folding aligns and strengthens the gluten gently while redistributing heat and gas. It is ideal for hand bakers and for wetter doughs that are hard to knead.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Which statement about hand kneading is most accurate?', 'multiple_choice', '{"A": "Hand kneading develops gluten well but takes longer and is easier to judge by feel", "B": "Hand kneading cannot develop gluten properly and always gives poor bread", "C": "Hand kneading should be done for exactly 2 minutes", "D": "Hand kneading requires the dough to be hot"}'::jsonb, 'A', 'Hands develop gluten perfectly well, just more slowly than a machine, and you can feel the dough tighten and smooth out. That feel is a reliable guide to when it is ready.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Adding fat such as oil or butter to a bread dough mainly does what?', 'multiple_choice', '{"A": "Speeds up gluten formation dramatically", "B": "Makes the crust much harder", "C": "Replaces the need for yeast", "D": "Makes the crumb softer and improves keeping quality"}'::jsonb, 'D', 'Fat coats gluten strands and starch, shortening the crumb and slowing staling. This is why enriched breads stay soft longer than a plain lean loaf.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Why is it usually better to add fat after the gluten has begun to develop rather than at the very start?', 'multiple_choice', '{"A": "Fat added early coats the flour and slows water absorption and gluten formation", "B": "Fat added early kills the yeast", "C": "Fat added early makes the dough taste bitter", "D": "Fat added early causes the salt to dissolve too fast"}'::jsonb, 'A', 'A film of fat around the flour particles hinders hydration and gluten bonding, lengthening the mix. Adding it once the dough has some structure gives a shorter, more reliable mix.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Why do wholemeal doughs generally need more water than white doughs?', 'multiple_choice', '{"A": "Because bran and germ absorb extra water", "B": "Because wholemeal flour contains no gluten", "C": "Because wholemeal flour is heavier per litre", "D": "Because wholemeal ferments faster"}'::jsonb, 'A', 'The bran and germ are thirsty and keep absorbing water during the mix and rest. Without extra water a wholemeal dough bakes dry and dense.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'What effect do sharp bran particles have on a wholemeal dough''s structure?', 'multiple_choice', '{"A": "They strengthen the gluten network", "B": "They have no effect at all", "C": "They can cut through gluten strands, reducing rise", "D": "They convert starch into sugar"}'::jsonb, 'C', 'Bran flakes physically interrupt the gluten network, so wholemeal loaves rise less than white ones. Soaking the bran or resting the dough softens the edges and limits the damage.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'What is the main practical purpose of the bench rest (intermediate proof) between dividing and final shaping?', 'multiple_choice', '{"A": "To cool the dough right down", "B": "To let the gluten relax so the pieces shape without tearing", "C": "To let the crust form", "D": "To add more yeast"}'::jsonb, 'B', 'Dividing tightens the dough, and a short rest lets the gluten relax so it stretches instead of springing back. This gives neater shaping and better final volume.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Why is weighing ingredients on a scale better than measuring by cups for bread?', 'multiple_choice', '{"A": "Cups are illegal in commercial baking", "B": "Scales are faster to wash", "C": "Scooped flour varies a lot in weight, so results become inconsistent", "D": "Cups cannot hold enough flour"}'::jsonb, 'C', 'The weight of a cup of flour changes with how it is scooped and how humid the air is, sometimes by a large margin. Weighing gives repeatable dough every single time, which is what a business needs.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Your dough is very sticky and hard to handle. What is the best first response?', 'multiple_choice', '{"A": "Let it rest briefly, use wet or lightly oiled hands and a bench scraper, and give it time to develop", "B": "Add plenty of extra flour immediately until it stops sticking", "C": "Add extra yeast", "D": "Put it straight into the oven"}'::jsonb, 'A', 'Much stickiness disappears as the flour hydrates and gluten develops, so resting and gentle handling usually solve it. Dumping in flour changes the recipe and gives a dry, tight loaf.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Why is a tight, well-sealed seam important when shaping a loaf?', 'multiple_choice', '{"A": "It makes the loaf shinier", "B": "It creates surface tension that holds the loaf''s shape and directs the rise upwards", "C": "It stops the yeast escaping", "D": "It reduces the baking time by half"}'::jsonb, 'B', 'A taut skin and sealed seam keep gas trapped and stop the loaf spreading sideways. A loose seam can burst open in the oven and let the loaf flatten.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3), 'Water in a bread dough does all of the following EXCEPT:', 'multiple_choice', '{"A": "Hydrate the flour proteins so gluten can form", "B": "Dissolve salt and sugar and let yeast work", "C": "Control dough temperature and consistency", "D": "Provide the protein that makes gluten"}'::jsonb, 'D', 'Water enables gluten formation but supplies no protein itself; the protein comes from the flour. Its role is hydration, solution, temperature control and dough consistency.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=3);
-- expect 20
