-- Using CORRECT column names from actual database schema
-- =================================================================================

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('64e43c02-a817-42ce-8877-5929e5c76a52', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('84d4df93-67e6-448c-8c01-6538b9dddad4', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('3bcc47e7-883e-48e2-96dc-ee41bad53e48', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('c8611d21-206f-4451-bed4-06deb144b006', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('962d0ef0-e152-4b89-8a21-df55c594243d', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('a6c8089a-7d73-4217-adcb-23d50b39fec0', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('97331b53-bb8f-4169-a904-9e1fcc43e596', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('87be1a69-634d-40a8-9774-af25163f0af7', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('1a031389-d8f8-4a3d-9299-d93f96e7d0a4', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('9dfcde1b-5589-4d5e-9180-d205d4468a49', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('dcaaf6df-9253-48e2-aa27-8ffb426e9992', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('a2304fb7-220a-4162-a8ab-e91d995d0593', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('d72c0380-2d7a-4bdc-b24e-95a4e7d37790', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('d44d4c27-5f16-4d58-8458-f21c17f1ae62', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('57bb0d45-5e6e-4f76-b285-0c8153f8a812', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('1551f95c-f7f3-478b-9a5c-f888eec9ed51', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('e89cf036-129a-43bd-bff5-8c96b20fee87', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('d47d2e6a-e5d4-45f6-8059-9e84cca1f189', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('f90335b0-bf8f-4a31-a610-9d6220edfd34', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('c7fc7116-7e0a-4a8d-89a0-1d9748c3e429', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('642d0d71-16ef-46f5-9f3f-1cfc900df706', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('14b6d99a-a809-4cbf-9b50-407dbfb0cecf', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('5d04f957-1d55-49fc-b8eb-a621aa1b309a', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('c0214bd7-f7a7-4a09-ab10-70e3a0cb73f1', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('aac5a928-00e4-42c6-a23f-ac92c685eb4f', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('60607a9d-cbc5-44b9-86bc-889f759d61ec', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('82c7afaf-4196-49e9-867e-4ec4ab5c7725', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('40bcd87e-329a-40b1-8dbc-6ea0ea188cba', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('0c48f1de-6fe4-4870-965d-815a9a430a8f', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('da063670-96e1-4ac4-9ef4-f5a6c6bcc166', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('1dbb8ef3-e7c6-47c2-9bb4-9caf6e9594de', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('8d6ab119-3894-4e7a-8ba6-63edd170b135', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('e97ee07a-2902-42b9-8aae-d48efa28287b', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('274046b3-d052-4203-af77-f58052048061', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('bc0d527a-bf09-4f39-a902-36b57e1a3afe', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('6ca12608-3841-494d-b665-b90fe598c60d', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('669364ca-73c5-4273-ac35-aff218f2ffde', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('9803a0f3-e9f6-4cf9-8a86-7c44433822ca', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('8fbd9e92-242b-4dd6-9029-1cff0e24adfb', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('5460edd6-a4da-4a4a-9bd5-a352e24703a9', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('956b52bf-a202-4248-bf45-d2b6058a4a39', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('cd8315cc-73d5-4192-bc9d-7bfa59a2d138', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('818a5bbc-20fb-449a-84d9-b69a513f85d4', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('dd169961-8e43-40dc-81d7-64fc5a0bbe39', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('c9d6672b-1adc-47c1-8d9b-649e6816f336', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

INSERT INTO viability_checklists (course_id, prerequisite_skills, capital_requirement_min, capital_requirement_recommended, capital_requirement_ideal, space_requirements, time_commitment_hours_per_week, legal_requirements, safety_considerations, family_lifestyle_impact, risk_assessment, resource_availability, market_validation_steps)
VALUES ('90c0b430-fe20-4ff3-853c-3a411f657f95', '"[\"Basic business management\", \"Customer service\", \"Quality control\", \"Simple accounting\", \"Time management\"]"'::jsonb, 1000, 2000, 3500, '200 sqft', 20, '"[\"Business registration\", \"Tax number\", \"Health permits\", \"Food safety\", \"Insurance\"]"'::jsonb, 'Standard safety precautions', 'Moderate time commitment, manageable with family support', '"[\"Market saturation\", \"Supply chain issues\", \"Quality problems\", \"Price competition\", \"Seasonal variation\"]"'::jsonb, 'Supplier ecosystem exists, reliable', '"[\"Survey 20+ customers\", \"Test product\", \"Research competition\", \"Calculate revenue\", \"Document learnings\"]"'::jsonb);

COMMIT;
