-- CORRECTED: Using actual course UUIDs from database
-- =================================================================================

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('64e43c02-a817-42ce-8877-5929e5c76a52', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('84d4df93-67e6-448c-8c01-6538b9dddad4', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('3bcc47e7-883e-48e2-96dc-ee41bad53e48', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('c8611d21-206f-4451-bed4-06deb144b006', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('962d0ef0-e152-4b89-8a21-df55c594243d', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('a6c8089a-7d73-4217-adcb-23d50b39fec0', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('97331b53-bb8f-4169-a904-9e1fcc43e596', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('87be1a69-634d-40a8-9774-af25163f0af7', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('1a031389-d8f8-4a3d-9299-d93f96e7d0a4', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('9dfcde1b-5589-4d5e-9180-d205d4468a49', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('dcaaf6df-9253-48e2-aa27-8ffb426e9992', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('a2304fb7-220a-4162-a8ab-e91d995d0593', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('d72c0380-2d7a-4bdc-b24e-95a4e7d37790', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('d44d4c27-5f16-4d58-8458-f21c17f1ae62', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('57bb0d45-5e6e-4f76-b285-0c8153f8a812', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('1551f95c-f7f3-478b-9a5c-f888eec9ed51', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('e89cf036-129a-43bd-bff5-8c96b20fee87', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('d47d2e6a-e5d4-45f6-8059-9e84cca1f189', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('f90335b0-bf8f-4a31-a610-9d6220edfd34', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('c7fc7116-7e0a-4a8d-89a0-1d9748c3e429', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('642d0d71-16ef-46f5-9f3f-1cfc900df706', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('14b6d99a-a809-4cbf-9b50-407dbfb0cecf', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('5d04f957-1d55-49fc-b8eb-a621aa1b309a', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('c0214bd7-f7a7-4a09-ab10-70e3a0cb73f1', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('aac5a928-00e4-42c6-a23f-ac92c685eb4f', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('60607a9d-cbc5-44b9-86bc-889f759d61ec', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('82c7afaf-4196-49e9-867e-4ec4ab5c7725', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('40bcd87e-329a-40b1-8dbc-6ea0ea188cba', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('0c48f1de-6fe4-4870-965d-815a9a430a8f', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('da063670-96e1-4ac4-9ef4-f5a6c6bcc166', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('1dbb8ef3-e7c6-47c2-9bb4-9caf6e9594de', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('8d6ab119-3894-4e7a-8ba6-63edd170b135', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('e97ee07a-2902-42b9-8aae-d48efa28287b', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('274046b3-d052-4203-af77-f58052048061', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('bc0d527a-bf09-4f39-a902-36b57e1a3afe', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('6ca12608-3841-494d-b665-b90fe598c60d', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('669364ca-73c5-4273-ac35-aff218f2ffde', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('9803a0f3-e9f6-4cf9-8a86-7c44433822ca', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('8fbd9e92-242b-4dd6-9029-1cff0e24adfb', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('5460edd6-a4da-4a4a-9bd5-a352e24703a9', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('956b52bf-a202-4248-bf45-d2b6058a4a39', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('cd8315cc-73d5-4192-bc9d-7bfa59a2d138', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('818a5bbc-20fb-449a-84d9-b69a513f85d4', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('dd169961-8e43-40dc-81d7-64fc5a0bbe39', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('c9d6672b-1adc-47c1-8d9b-649e6816f336', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('90c0b430-fe20-4ff3-853c-3a411f657f95', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

COMMIT;
