-- Agro-forestry & Fruit Processing - Module 1, 20 real questions
-- Paste the WHOLE file, press Run. Safe to re-run.
ALTER TABLE quiz_questions ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE quizzes ALTER COLUMN id SET DEFAULT gen_random_uuid();

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1);
DELETE FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '241c555f-fd61-4479-ad16-245572c8a5e4', 'Module 1 Assessment', 'Twenty questions on the fundamentals of Agro-forestry & Fruit Processing.', 70, 30, 'module', 'beginner', 1);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'You want to dry mango slices for sale. At what stage should you harvest the fruit?', 'multiple_choice', '{"A": "Fully green and hard, so it survives transport to the drying shed", "B": "Firm-ripe, when the flesh has developed full colour and sweetness but still holds its shape when sliced", "C": "Over-ripe and soft, because soft fruit dries fastest", "D": "Any stage, since drying removes the differences between them"}'::jsonb, 'B', 'Sugar and flavour develop on the tree, so green fruit dries into a bland, sour product, while over-ripe fruit collapses into mush and sticks to the trays. Firm-ripe fruit gives full flavour and slices that keep their shape.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'A processor dries fruit by spreading it on mats on bare ground in the open sun. What is the main food-safety problem with this?', 'multiple_choice', '{"A": "The fruit dries too quickly and case-hardens", "B": "Sunlight destroys all the sugar in the fruit", "C": "The fruit is exposed to dust, soil, insects, birds and animal droppings, which contaminate it", "D": "Open sun drying makes the fruit too acidic to sell"}'::jsonb, 'C', 'Direct ground drying is the commonest route for soil bacteria, flies and rodent or bird droppings to reach the product. A raised, screened solar dryer keeps fruit off the ground, away from pests, and usually dries faster too.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'One of your workers has had diarrhoea since yesterday but wants to come in and help peel fruit. What is the correct action?', 'multiple_choice', '{"A": "Keep the worker away from all food handling until they are symptom-free, then let them return", "B": "Let them work but give them gloves, since gloves stop all germs", "C": "Let them work only on peeling, since the fruit is cooked later anyway", "D": "Let them work but ask them to wash hands twice as often"}'::jsonb, 'A', 'Diarrhoea means the worker may be shedding organisms such as Salmonella or E. coli, and gloves or extra hand-washing do not remove that risk. Excluding sick food handlers until they recover is a basic rule in every food hygiene code.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'Why do agro-forestry systems favour leguminous trees such as Gliricidia, Leucaena or Calliandra alongside crops?', 'multiple_choice', '{"A": "Their roots are shallow, so they never compete with crops for water", "B": "They grow so slowly that they never need pruning", "C": "They repel all insect pests from the field", "D": "Their root nodules host bacteria that fix nitrogen from the air, and their prunings return nitrogen-rich material to the soil"}'::jsonb, 'D', 'Legume trees form nodules with rhizobia bacteria that convert atmospheric nitrogen into a form plants can use. Cutting the leafy prunings onto the field as mulch transfers that nitrogen to the crop and adds organic matter.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'Many vegetables and some fruits are blanched (dipped briefly in hot water or steam) before drying. What is the main purpose?', 'multiple_choice', '{"A": "To add sweetness so less sugar is needed later", "B": "To inactivate the enzymes that cause browning and off-flavours during drying and storage", "C": "To increase the weight of the finished dried product", "D": "To remove the pesticide residues completely"}'::jsonb, 'B', 'Enzymes such as polyphenol oxidase keep working in a drying slice and turn it brown and stale-tasting even when no microbes are present. A short heat treatment destroys them and also loosens skins and reduces surface microbes.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'When loading a solar dryer with fruit slices, why does it matter that all slices are cut to the same thickness?', 'multiple_choice', '{"A": "Because customers pay by the number of slices, not by weight", "B": "Because thick slices burn while thin slices stay wet", "C": "Because slices of different thickness finish drying at different times, so thin ones over-dry while thick ones stay damp and spoil the whole batch", "D": "Because uneven slices block the sunlight from reaching the tray"}'::jsonb, 'C', 'A single damp slice packed with dry ones raises the moisture of the whole pack and lets mould start. Cutting to a uniform thickness, commonly about 5-8 mm (roughly 1/4 in) for mango, makes the whole tray finish together.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'Your dried pineapple comes out of the dryer hot. Why must you let it cool before sealing it into bags?', 'multiple_choice', '{"A": "Warm fruit gives off moisture that condenses inside the sealed bag and lets mould grow", "B": "Hot fruit will bleach the printing on the label", "C": "Cooling makes the fruit heavier so you get more packs per batch", "D": "Sealing hot fruit removes its sweetness"}'::jsonb, 'A', 'Sealing while warm traps water vapour, which condenses into droplets on the inside of the bag as it cools and rewets the surface of the fruit. Cool to room temperature in a clean, covered place first, then seal.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'Which packaging and storage practice best protects dried fruit through several months of shelf life?', 'multiple_choice', '{"A": "Open woven sacks stored on the floor of the store room", "B": "Clear thin polythene bags kept on a sunny window shelf so buyers can see the colour", "C": "Paper bags stacked next to the cooking area where it is warm and dry", "D": "Sealed moisture-proof bags, stored off the floor in a cool, dark, dry room"}'::jsonb, 'D', 'Dried fruit fails mainly by re-absorbing moisture from humid air and by light and heat fading its colour and flavour. A well-sealed moisture barrier kept cool and dark addresses all three at once.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'You are boiling fruit jam without a refractometer. Which boiling temperature is the classic indicator that the jam has reached setting point at sea level?', 'multiple_choice', '{"A": "About 85 degrees C (185 F)", "B": "About 105 degrees C (221 F), roughly 4-5 degrees C above the boiling point of water", "C": "About 120 degrees C (248 F)", "D": "About 140 degrees C (284 F)"}'::jsonb, 'B', 'As water boils off, the sugar concentration rises and pushes the boiling point above 100 degrees C (212 F); around 104-105 degrees C corresponds to the roughly 65 percent soluble solids a jam needs to set. At high altitude water boils lower, so the target moves down with it.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'A properly made jam contains roughly 65 percent sugar (soluble solids). Why does that level of sugar preserve the jam?', 'multiple_choice', '{"A": "Sugar is a poison that kills bacteria on contact", "B": "Sugar makes the jam acidic enough to stop all microbes", "C": "The dissolved sugar ties up the water so little is available for moulds, yeasts and bacteria to grow", "D": "Sugar seals the surface of the jar so no air can enter"}'::jsonb, 'C', 'Preservation here works by lowering water activity, not by any toxic effect of sugar. This is why low-sugar jams spoil far faster and must be refrigerated or otherwise preserved.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'You are bottling hot jam into glass jars in a small workshop. Which practice gives the safest seal?', 'multiple_choice', '{"A": "Fill the jars while the jam is still very hot into clean, hot, sterilised jars, leaving a small headspace, then cap immediately", "B": "Let the jam cool to room temperature first, then fill so the glass does not crack", "C": "Fill to the very brim so no air at all is left in the jar", "D": "Fill hot into cold jars straight from the store to help the jam set quickly"}'::jsonb, 'A', 'Hot filling into hot sterilised jars heats the jar and lid surfaces and, as the contents cool and contract, pulls a vacuum that seals the lid. Cold jam or a cold jar leaves surviving mould spores and no vacuum, and filling to the brim leaves no space for that vacuum to form.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'You want to bottle a low-acid fruit pulp such as ripe pawpaw or banana and keep it without refrigeration, using only a boiling water bath. What must you do first?', 'multiple_choice', '{"A": "Add extra sugar until it tastes sweet enough", "B": "Add extra salt, which controls the same organisms", "C": "Boil it for twice as long, which makes acid unnecessary", "D": "Acidify it with lemon juice or citric acid to bring the pH below about 4.5, or process it in a pressure retort instead"}'::jsonb, 'D', 'Clostridium botulinum spores survive boiling water temperatures and can grow in sealed low-acid foods, so boiling alone is not enough. Bringing the pH below roughly 4.6 stops the spores from germinating, which is why acid foods can safely be water-bath processed.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'Faidherbia albida is valued in dryland parkland farming because of its unusual leaf habit. What is it?', 'multiple_choice', '{"A": "It keeps its leaves all year, giving crops constant shade", "B": "It sheds its leaves at the start of the rains and leafs out in the dry season, so it shades crops least when they need sunlight most", "C": "It sheds its leaves only once every three years", "D": "Its leaves close at night to trap dew for the crop below"}'::jsonb, 'B', 'This reversed phenology means the tree is bare during the cropping season, so cereals grown beneath it get full light while benefiting from the leaf litter it dropped and from its nitrogen fixation. It is the reason farmers can keep mature trees standing right in their maize or millet fields.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'A nursery operator wants seedlings of a mango variety that reliably produce the same fruit as the mother tree. What should they do?', 'multiple_choice', '{"A": "Sow seed from the best fruit of that tree, since seed carries the variety", "B": "Sow seed but water it more heavily to fix the variety", "C": "Graft or bud scion wood taken from the mother tree onto a seedling rootstock", "D": "Plant several seeds in one pot so the strongest one keeps the variety"}'::jsonb, 'C', 'Seedlings from cross-pollinated fruit trees are genetically variable and usually do not match the parent in fruit quality or time to bearing. Grafting clones the mother tree''s wood onto a rootstock, so the fruit is true to type and the tree bears years earlier.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'A buyer asks for the Brix of your fruit juice. What does a hand refractometer actually measure?', 'multiple_choice', '{"A": "The percentage of dissolved solids, mostly sugars, in the juice", "B": "The acidity or pH of the juice", "C": "The number of bacteria per millilitre", "D": "The vitamin C content"}'::jsonb, 'A', 'A refractometer reads how much the dissolved solids bend light, reported as degrees Brix, which for fruit juice is dominated by sugars. It tells you about sweetness and concentration but says nothing about acidity or microbial safety, which need a pH meter and hygiene control.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'In alley cropping, hedgerows of fast-growing trees are planted between strips of annual crops. What routine management keeps the system productive?', 'multiple_choice', '{"A": "Leave the hedges unpruned so they grow tall and produce more mulch", "B": "Uproot and replant the hedgerows every season", "C": "Prune only once the crop has already failed from shading", "D": "Cut the hedges back repeatedly during the cropping season and spread the prunings as mulch on the crop alleys"}'::jsonb, 'D', 'Unpruned hedgerows shade the crop and compete for water and nutrients, cancelling out the benefit. Regular cutting keeps them low while the prunings deliver nitrogen and organic matter exactly where the crop is growing.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'You use sodium metabisulphite as a pre-treatment dip to keep dried mango bright in colour. What must you do on the pack?', 'multiple_choice', '{"A": "Nothing, because the sulphite evaporates during drying", "B": "Declare the sulphites on the label, because they are a recognised allergen that some asthmatics react to", "C": "Declare it only if the buyer is an exporter", "D": "Describe it as a natural colour on the ingredient list"}'::jsonb, 'B', 'Residual sulphite remains in the dried fruit and can trigger severe reactions in sulphite-sensitive people, so food laws in most markets require it to be declared. Undeclared sulphite is one of the commonest reasons small dried-fruit consignments are rejected.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'Fruit fly maggots are ruining your mango supply. Which measure does most to reduce the population on the farm?', 'multiple_choice', '{"A": "Harvesting all fruit as late as possible so it is fully ripe", "B": "Pruning trees hard so they carry fewer fruit", "C": "Collecting fallen and infested fruit regularly and destroying it by deep burial, boiling or sealed bagging, so the maggots cannot complete their life cycle", "D": "Watering the orchard more often to drown the larvae"}'::jsonb, 'C', 'Maggots leave fallen fruit, pupate in the soil and emerge as the next generation of flies, so rotting fruit left under the trees is the population''s engine. Consistent orchard sanitation, combined with early harvest and traps, breaks that cycle.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'Drying fruit removes most of its water, so it takes several kilograms of fresh fruit to make one kilogram of dried. What does this mean when you set your selling price?', 'multiple_choice', '{"A": "The price per kilogram of the dried product must cover the cost of all the fresh fruit that went into it, plus peeling and trimming losses, fuel, labour and packaging", "B": "The dried product should be priced per kilogram at about the same rate as fresh fruit", "C": "Weight loss during drying is a gain, because you sell the water separately", "D": "Fresh fruit cost can be ignored because it is bought before the business earns anything"}'::jsonb, 'A', 'If one kilogram of dried mango consumes several kilograms of fresh fruit plus the peel and stone that are thrown away, pricing at anything near the fresh rate guarantees a loss. Work out your true fresh-to-dried yield on a real batch and build your price up from that measured figure.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1), 'You sell jam at a fixed price per jar. Your monthly rent, licence and equipment costs stay the same whether you make 100 jars or 500. Which calculation tells you how many jars you must sell each month before you start making a profit?', 'multiple_choice', '{"A": "The total revenue from last month divided by the number of jars sold", "B": "The cost of fruit and sugar per jar multiplied by the number of jars produced", "C": "Fixed monthly costs divided by the contribution per jar, that is the selling price minus the variable cost of fruit, sugar, jar, lid, label and fuel for that jar", "D": "The selling price per jar multiplied by the number of jars you hope to sell"}'::jsonb, 'C', 'Each jar sold contributes its price minus its own variable cost towards paying the fixed costs, so the break-even volume is fixed costs divided by that contribution. Knowing this number tells you whether your price and your production capacity can actually carry the business.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='241c555f-fd61-4479-ad16-245572c8a5e4' AND quiz_sequence=1);
-- expect 20
