-- Bead & Jewelry Making - Module 1, 20 real questions
-- Paste the WHOLE file, press Run. Safe to re-run.
ALTER TABLE quiz_questions ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE quizzes ALTER COLUMN id SET DEFAULT gen_random_uuid();

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1);
DELETE FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '499b113c-2644-4125-8042-de8dfe1416e6', 'Module 1 Assessment', 'Twenty questions on the fundamentals of Bead & Jewelry Making.', 70, 30, 'module', 'beginner', 1);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'Seed beads are labelled 6/0, 8/0, 11/0 and 15/0. Which of these is the SMALLEST bead?', 'multiple_choice', '{"A": "6/0, about 3.7 mm (0.15 in)", "B": "8/0, about 3.0 mm (0.12 in)", "C": "11/0, about 2.2 mm (0.09 in)", "D": "15/0, about 1.5 mm (0.06 in)"}'::jsonb, 'D', 'Seed bead sizing is inverse: the number is roughly how many beads fit end-to-end in 25 mm (1 in), so a bigger number means a smaller bead. 15/0 is therefore the finest of the four and 6/0 the chunkiest.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'You need the THICKEST wire for a strong ear-wire or a bangle frame. Which gauge do you buy?', 'multiple_choice', '{"A": "26 gauge, about 0.4 mm (0.016 in)", "B": "24 gauge, about 0.5 mm (0.020 in)", "C": "20 gauge, about 0.8 mm (0.032 in)", "D": "18 gauge, about 1.0 mm (0.040 in)"}'::jsonb, 'D', 'Wire gauge also runs backwards: the higher the gauge number, the thinner the wire. 18 gauge (~1.0 mm) is the heaviest listed and holds a shape under load, while 26 gauge is fine wrapping wire that will bend out of shape.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'A customer says cheap earrings make her earlobes itch, redden and weep. Which metal is the most common cause of this reaction?', 'multiple_choice', '{"A": "Copper", "B": "Nickel", "C": "Titanium", "D": "Pure gold"}'::jsonb, 'B', 'Nickel is by far the commonest cause of allergic contact dermatitis from jewellery, and it is hidden in most cheap plated base-metal findings. Copper may leave a harmless green mark on skin, while titanium and pure gold rarely provoke allergy.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'Which knot is the standard choice for finishing a stretch-cord (elastic) bracelet?', 'multiple_choice', '{"A": "A single overhand knot", "B": "A simple bow", "C": "A surgeon''s knot", "D": "A slip knot"}'::jsonb, 'C', 'A surgeon''s knot is a square knot with an extra pass on the first half, so the extra friction stops the slippery elastic sliding loose while you tie the second half. Finish with a dab of jeweller''s glue and hide the knot inside a bead hole.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'You have strung a necklace on flexible multi-strand beading wire (tiger tail type). How should the ends be attached to the clasp?', 'multiple_choice', '{"A": "Squash a crimp tube over the doubled wire with crimping pliers", "B": "Tie a double overhand knot and add a drop of glue", "C": "Tie the wire directly to the clasp with a surgeon''s knot", "D": "Melt the wire end with a flame to form a stop"}'::jsonb, 'A', 'Flexible beading wire is many fine steel strands under a nylon coat; a knot crushes and kinks those strands so the wire fatigues and snaps. A crimp tube spreads the grip along the wire, which is why every stringing project on this wire ends in a crimp.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'Which pliers do you use to form a neat round loop on the end of a headpin?', 'multiple_choice', '{"A": "Flat-nose pliers", "B": "Round-nose pliers", "C": "Chain-nose (needle-nose) pliers", "D": "Crimping pliers"}'::jsonb, 'B', 'Round-nose pliers have two smooth tapering cones, so the wire wraps around them into a true circle, and moving nearer the tip gives a smaller loop. Flat and chain-nose jaws would put a crease or flat spot in the loop.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'What is the correct way to open a jump ring so it closes again invisibly and stays strong?', 'multiple_choice', '{"A": "Pull the two ends straight apart, widening the circle", "B": "Cut the ring and solder it after fitting", "C": "Squeeze the ring into an oval until the gap opens", "D": "Grip each side with pliers and twist one end sideways, away from you"}'::jsonb, 'D', 'Twisting laterally keeps the ring''s round shape, so the two ends meet flush again with no gap for a chain link to escape. Pulling the ends apart stretches the circle permanently and the ring never closes tightly again.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'A finding stamped "925" tells you it is:', 'multiple_choice', '{"A": "Sterling silver, 92.5% silver alloyed with other metal", "B": "Silver-plated over brass", "C": "Pure 100% silver", "D": "Stainless steel polished to look like silver"}'::jsonb, 'A', '925 is the sterling standard: 92.5% fine silver with about 7.5% other metal (usually copper) added for hardness, since pure silver is too soft for clasps and ear wires. It will darken with sulphur in the air, so store finished pieces in a sealed bag with the air pressed out.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'Why do quality pearl and gemstone necklaces have a knot tied between every bead?', 'multiple_choice', '{"A": "It makes the necklace hang longer using fewer beads", "B": "It is only decoration, with no functional purpose", "C": "If the thread breaks, only one bead can fall off, and the beads cannot rub each other", "D": "It stops the thread stretching over time"}'::jsonb, 'C', 'Each knot acts as a stopper, so a break loses one bead instead of scattering the whole strand, and the knot cushions the beads so their drill holes do not grind the thread or chip each other. This is the detail customers use to tell hand-finished work from mass-market strands.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'Crimping pliers have two notches. How are they used correctly on a crimp tube?', 'multiple_choice', '{"A": "Use only the outer oval notch, squeezing twice", "B": "First the inner notch to fold the tube into a crescent around the two wires, then the outer notch to round it off", "C": "First the outer notch, then the inner notch to flatten the tube completely", "D": "Either notch is fine, they only differ in size"}'::jsonb, 'B', 'The inner (crescent) notch presses a ridge between the two wire strands so each strand is gripped separately, then the outer notch folds that crescent into a neat round bead. A crimp simply flattened is weaker and has sharp edges that catch on clothing and skin.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'A batch of stone beads has holes too small or too rough for your thread. The correct tool is a:', 'multiple_choice', '{"A": "Bench vice", "B": "Wire cutter", "C": "Bead scoop", "D": "Bead reamer"}'::jsonb, 'D', 'A bead reamer is a fine diamond-coated point that enlarges and smooths a drill hole, used wet so the stone does not overheat and crack. Smoothing a rough hole also removes the sharp edge that silently saws through thread over months of wear.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'What tension should you aim for when stringing a beaded necklace?', 'multiple_choice', '{"A": "Slightly slack, so the strand drapes and curves easily with no gaps showing", "B": "As tight as you can pull it, so no wire is visible at all", "C": "Very loose, with visible thread between each bead", "D": "Tension does not matter once the clasp is attached"}'::jsonb, 'A', 'A little slack lets the beads shift and the strand follow the neck or wrist, which spreads the load instead of concentrating it. Strung bone-tight, the strand stands stiff, kinks at the crimp and the wire work-hardens and breaks there.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'When you work out the cost of a bracelet to set your price, which of these is most often left out by beginners and must be included?', 'multiple_choice', '{"A": "The cost of the beads", "B": "The cost of the clasp", "C": "Your own working time, plus breakage and offcut waste", "D": "The cost of the thread"}'::jsonb, 'C', 'Beginners price only the visible materials and end up paying themselves nothing, so the business cannot grow or replace tools. Cost your hours at a real hourly rate and add a wastage allowance for broken beads and cut-off thread before adding any profit margin.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'A strand of 100 beads costs 500 units. Each bracelet uses 36 of those beads, one clasp at 40 units and cord costing 20 units. What is the material cost of one bracelet?', 'multiple_choice', '{"A": "240 units", "B": "180 units", "C": "560 units", "D": "120 units"}'::jsonb, 'A', 'Break bulk down to a unit cost first: 500 / 100 = 5 units per bead, so 36 beads cost 180, plus 40 for the clasp and 20 for cord gives 240. Costing per piece rather than per purchase is what tells you whether a design actually earns money.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'You are weaving with 11/0 seed beads and must pass the thread through each bead several times. Which needle is finer?', 'multiple_choice', '{"A": "A size 10 beading needle", "B": "A size 12 beading needle", "C": "They are identical in thickness", "D": "Whichever is longer is finer"}'::jsonb, 'B', 'Like bead and wire sizing, beading needle numbers run backwards, so size 12 is thinner than size 10 and leaves room for the extra thread passes. Needle length is a separate choice and says nothing about thickness.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'Your beadwork keeps failing because glass bugle beads and crystals cut the thread. What is the best fix?', 'multiple_choice', '{"A": "Double the nylon thread and pull tighter", "B": "Wax the nylon thread more heavily", "C": "Use a thicker nylon monofilament", "D": "Switch to a braided gel-spun thread and put a round seed bead at each end of the sharp bead"}'::jsonb, 'D', 'Braided gel-spun threads (FireLine, WildFire and similar) resist the sawing action of a sharp glass edge far better than nylon of any thickness. Capping each bugle or crystal with a small round bead keeps the thread off the cut edge entirely, which is the real cure.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'You want to sell earrings that are safe for customers with sensitive ears. Which ear wire do you stock?', 'multiple_choice', '{"A": "Nickel silver (German silver) wires", "B": "Silver-plated base metal wires", "C": "Surgical stainless steel or titanium wires", "D": "Brass wires with a clear lacquer coat"}'::jsonb, 'C', 'Surgical stainless steel and titanium either contain no nickel or lock it in so little is released onto the skin. Nickel silver contains nickel despite the name, and plating or lacquer wears through at exactly the point that sits in the piercing.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'For a heavy stone pendant hanging on a chain, which loop should join the pendant to the chain?', 'multiple_choice', '{"A": "A simple (plain) loop, because it is faster to make", "B": "A wrapped loop, where the wire tail is coiled around the stem", "C": "A simple loop squeezed shut with flat-nose pliers", "D": "An open jump ring left slightly apart so it moves freely"}'::jsonb, 'B', 'A simple loop is only held closed by the springiness of the wire, so weight and daily movement work it open and the pendant is lost. The wrapped loop''s coiled tail closes the circle permanently, which is why it is standard for anything heavy or valuable.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'Before packing finished necklaces for sale, what is the single most useful quality check?', 'multiple_choice', '{"A": "Give a firm steady pull on the strand at both clasp ends and check each crimp and knot holds", "B": "Weigh each piece to confirm it matches the design", "C": "Count the beads to confirm the pattern is symmetrical", "D": "Photograph each piece for your records"}'::jsonb, 'A', 'Almost all field failures happen at the connections, so a deliberate tug test finds the weak crimp or knot in your workshop instead of on a customer''s neck. Check at the same time that no wire tail or sharp crimp edge is left exposed.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1), 'A customer''s wrist measures 16 cm (6.3 in) and you are making her bracelet from 8 mm (5/16 in) round beads. What finished length, clasp included, should you make it?', 'multiple_choice', '{"A": "Exactly 16 cm (6.3 in)", "B": "About 16.5 cm (6.5 in)", "C": "About 17.5 to 18 cm (6.9 to 7.1 in)", "D": "About 19.5 cm (7.7 in)"}'::jsonb, 'C', 'A bracelet must be longer than the wrist because the beads sit around the outside of the wrist, not on the measuring line, and chunkier beads need more ease: roughly 1.5 to 2 cm (0.6 to 0.8 in) for 8 mm beads and less for small ones. Fitted to the exact wrist measurement it will not close, and 19.5 cm would slide over the hand.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='499b113c-2644-4125-8042-de8dfe1416e6' AND quiz_sequence=1);
-- expect 20
