-- Candle Making & Scent Blending - Module 1, 20 real questions
-- Paste the WHOLE file, press Run. Safe to re-run.
ALTER TABLE quiz_questions ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE quizzes ALTER COLUMN id SET DEFAULT gen_random_uuid();

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1);
DELETE FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '7618517c-88a8-4949-8cbf-bcc091271abc', 'Module 1 Assessment', 'Twenty questions on the fundamentals of Candle Making & Scent Blending.', 70, 30, 'module', 'beginner', 1);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'What is the typical melting point range of natural soy container wax?', 'multiple_choice', '{"A": "20-30 °C (68-86 °F)", "B": "45-55 °C (113-131 °F)", "C": "75-85 °C (167-185 °F)", "D": "100-110 °C (212-230 °F)"}'::jsonb, 'B', 'Soy container wax is a soft, low-melting wax that liquefies at roughly 45-55 °C (113-131 °F). This low melt point is why soy candles form a melt pool easily but also soften in hot storage.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Beeswax melts at approximately which temperature?', 'multiple_choice', '{"A": "38-42 °C (100-108 °F)", "B": "50-54 °C (122-129 °F)", "C": "62-65 °C (144-149 °F)", "D": "90-95 °C (194-203 °F)"}'::jsonb, 'C', 'Beeswax melts around 62-65 °C (144-149 °F), noticeably higher than soy or container paraffin. A higher melt point means the flame must work harder, so beeswax normally needs a larger wick.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Paraffin wax is produced from which raw material?', 'multiple_choice', '{"A": "Petroleum (crude oil) refining", "B": "Pressed palm fruit", "C": "Hydrogenated soybean oil", "D": "Secretions of the honey bee"}'::jsonb, 'A', 'Paraffin is a by-product of refining crude oil into fuels. Knowing the origin matters for buyers who ask for plant-based products and for how you describe your candles honestly.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Soy wax is made by which process?', 'multiple_choice', '{"A": "Boiling soybeans and skimming the surface", "B": "Hydrogenating soybean oil so it becomes solid at room temperature", "C": "Distilling soy leaves under pressure", "D": "Blending soy flour with paraffin"}'::jsonb, 'B', 'Soybean oil is hydrogenated, which raises its melting point so it is solid at room temperature. That is why soy wax is a processed product rather than a raw agricultural one.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Which wax type is generally cheapest per kilogram and gives the strongest hot scent throw, making it common in low-capital production?', 'multiple_choice', '{"A": "Beeswax", "B": "Coconut wax", "C": "Paraffin", "D": "Carnauba wax"}'::jsonb, 'C', 'Paraffin is widely available, low cost and holds and releases fragrance strongly. For a cottage business watching capital, it is the most forgiving and economical starting wax.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'A soy candle develops a pale, crystalline, frost-like film on its surface after a few days. What is this?', 'multiple_choice', '{"A": "Mould growth caused by damp storage", "B": "Frosting: a natural polymorphic crystal formation in soy wax", "C": "Fragrance oil separating out of the wax", "D": "Dye that has failed to dissolve"}'::jsonb, 'B', 'Frosting is soy wax re-crystallising at the surface and is purely cosmetic; it does not affect burn or scent. It is a sign of natural soy, not a defect, and cannot be fully prevented.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'What is the main difference between a container wax and a pillar wax?', 'multiple_choice', '{"A": "Container wax is scented at the factory; pillar wax is not", "B": "Pillar wax is harder with a higher melt point and shrinks on cooling to release from a mould", "C": "Container wax can only be used with wooden wicks", "D": "Pillar wax cannot hold fragrance oil at all"}'::jsonb, 'B', 'Pillar wax is formulated to be hard and to contract as it cools so the candle slips out of the mould. Container wax stays softer and is designed to cling to the inside of a jar.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Why should you not use soft soy container wax to make free-standing pillar candles?', 'multiple_choice', '{"A": "It is too soft to hold its shape and will slump or bend", "B": "It is chemically unsafe outside a container", "C": "It will not accept a wick", "D": "It cannot be coloured"}'::jsonb, 'A', 'Container wax has a low melt point and stays soft, so an unsupported pillar sags, especially in warm African conditions. Pillars need a harder wax or an added hardener such as stearic acid.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'What is stearic acid used for in candle making?', 'multiple_choice', '{"A": "To thin the wax so it pours more easily", "B": "To harden and opacify the wax and raise its melt point", "C": "To replace the wick in floating candles", "D": "To dissolve water-based colourants"}'::jsonb, 'B', 'Stearic acid is a hardening additive that makes wax firmer, whiter and slower burning. It is commonly used to stiffen softer waxes for pillars and moulded shapes.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Coconut wax in its pure form is best described as:', 'multiple_choice', '{"A": "Very hard and brittle, ideal for tapers", "B": "Very soft with a low melt point, so it is usually sold as a blend", "C": "Water soluble", "D": "Unable to carry fragrance"}'::jsonb, 'B', 'Pure coconut wax is extremely soft and low-melting, so suppliers blend it with soy, paraffin or a harder wax. Buying an unblended coconut wax often leads to candles that will not set firm.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Palm wax is chosen mainly for which visual characteristic?', 'multiple_choice', '{"A": "It stays perfectly transparent", "B": "It glows in the dark", "C": "It forms crystalline feathered or snowflake patterns as it cools", "D": "It never shrinks"}'::jsonb, 'C', 'Palm wax crystallises into decorative feathered patterns when cooled at the right rate. The effect depends on pouring temperature and slow, undisturbed cooling.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Compared with paraffin, beeswax candles typically:', 'multiple_choice', '{"A": "Burn faster and drip more", "B": "Burn longer and slower because of the higher melt point", "C": "Carry added fragrance more strongly", "D": "Require a much smaller wick"}'::jsonb, 'B', 'Beeswax''s higher melt point means the fuel is consumed more slowly, giving a longer burn. Its own honey aroma also competes with added fragrance, so scent throw from added oils is weaker.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'How should bulk wax be stored in a home workshop?', 'multiple_choice', '{"A": "In open bags beside the cooker so it stays warm", "B": "Sealed, cool, dry and out of direct sunlight, away from strong-smelling goods", "C": "In a damp room to stop it cracking", "D": "Outdoors in the sun to keep it dry"}'::jsonb, 'B', 'Wax absorbs odours and dust and softens or discolours in heat and sunlight. Sealed, cool, dark storage keeps it clean and consistent between batches.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'The flash point of paraffin wax is roughly:', 'multiple_choice', '{"A": "60 °C (140 °F)", "B": "100 °C (212 °F)", "C": "200 °C (392 °F)", "D": "500 °C (932 °F)"}'::jsonb, 'C', 'Paraffin wax vapours can ignite at around 200 °C (392 °F). Melting temperatures are kept far below this, which is why wax must never be heated on a bare hotplate without a thermometer.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'What is the difference between a wax''s melting point and its flash point?', 'multiple_choice', '{"A": "They are two names for the same temperature", "B": "Melting point is where the wax turns liquid; flash point is where its vapours can ignite", "C": "Flash point is where the wax turns liquid; melting point is where it burns", "D": "Flash point only applies to fragrance oils, not to wax"}'::jsonb, 'B', 'Melting point is a physical change to liquid; flash point is the temperature at which enough vapour is given off to ignite near a spark or flame. Every wax and oil has both, and the gap between them is your safety margin.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Why do many makers use a paraffin-soy blend?', 'multiple_choice', '{"A": "To make the candle waterproof", "B": "To combine paraffin''s strong scent throw with soy''s smoother tops and slower burn", "C": "Because soy alone cannot be melted", "D": "To avoid needing a wick"}'::jsonb, 'B', 'Blends aim to keep the strong hot throw and easy handling of paraffin while gaining some of soy''s characteristics. Blends must still be wick-tested in their own right, as they behave like neither parent wax.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Patchy, cloudy marks where the wax has pulled away from the inside of the glass are called:', 'multiple_choice', '{"A": "Mushrooming", "B": "Tunnelling", "C": "Wet spots", "D": "Sinkholes"}'::jsonb, 'C', 'Wet spots are pockets of air where the cooling wax contracted and lost contact with the glass. They are cosmetic only and are worsened by cold jars and fast cooling.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Which wax is generally easiest to clean out of pots and jars with hot soapy water?', 'multiple_choice', '{"A": "Soy", "B": "Microcrystalline wax", "C": "Carnauba", "D": "Beeswax"}'::jsonb, 'A', 'Soy wax softens at low temperatures and washes out with hot soapy water more readily than harder waxes. Beeswax and microcrystalline wax cling stubbornly and are usually scraped out while warm.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Gel ''wax'' differs from true wax because it is:', 'multiple_choice', '{"A": "A mineral oil gelled with a polymer resin, not a wax at all", "B": "Simply paraffin with water added", "C": "A soy wax with extra dye", "D": "A powdered wax that sets when wet"}'::jsonb, 'A', 'Gel candle base is mineral oil thickened with a polymer resin, and it burns hotter and longer than wax. It requires gel-approved fragrance oils and non-flammable embeds, so it is not a good beginner product.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1), 'Which statement about buying wax for a new small business is most sound?', 'multiple_choice', '{"A": "Buy a full pallet of the cheapest wax available before testing", "B": "Buy a small quantity of one wax, master it, then scale up", "C": "Mix several unknown waxes together to save money", "D": "Choose wax based only on colour of the flakes"}'::jsonb, 'B', 'Every wax needs its own wick, temperature and fragrance testing, so mastering one wax first protects your cash and your quality. Buying large volumes before testing is how small makers lose their start-up capital.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='7618517c-88a8-4949-8cbf-bcc091271abc' AND quiz_sequence=1);
-- expect 20
