INSERT INTO course_business_profiles
(course_id, business_description, market_size, target_customer, competitive_landscape,
 unique_selling_proposition, revenue_model, scalability_potential, success_rate,
 time_to_profitability_months, avg_startup_investment, avg_monthly_revenue, profitability_timeline)
VALUES
('02dbd3f9-58dd-48ac-ae36-cbc091fb8091', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.8B annually, growing 12%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 80,
 6,
 2500,
 833,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('081b2b21-6383-44af-a764-5949f8637901', 
 'Professional business with proven market demand and scalability.',
 'Market size $12.5B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2200,
 733,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('0c48f1de-6fe4-4870-965d-815a9a430a8f', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.5B annually, growing 10%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1800,
 600,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('0da72775-079c-4e04-8db3-1fbebd28337a', 
 'Professional business with proven market demand and scalability.',
 'Market size $3.2B annually, growing 8%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2400,
 800,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('10a90a67-0084-4e29-98c6-ff1f1e39879b', 
 'Professional business with proven market demand and scalability.',
 'Market size $4.1B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1500,
 500,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('13c6032a-08df-4a8e-91ef-c607a7882b5f', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.3B annually, growing 13%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 80,
 6,
 2800,
 933,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('14b6d99a-a809-4cbf-9b50-407dbfb0cecf', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.8B annually, growing 15%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1200,
 400,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('15918f0b-4fd8-4af3-8b06-096b00052e56', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.9B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2000,
 666,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('169f0892-cc8d-40dc-ac77-836c5c79dc2c', 
 'Professional business with proven market demand and scalability.',
 'Market size $3.6B annually, growing 10%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 80,
 6,
 2500,
 833,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('1a031389-d8f8-4a3d-9299-d93f96e7d0a4', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.2B annually, growing 7%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1600,
 533,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('1dbb8ef3-e7c6-47c2-9bb4-9caf6e9594de', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.6B annually, growing 14%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 800,
 266,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('241c555f-fd61-4479-ad16-245572c8a5e4', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.8B annually, growing 12%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2100,
 700,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('274046b3-d052-4203-af77-f58052048061', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.0B annually, growing 8%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2200,
 733,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('2867d6c0-bb39-4519-95c0-c0434c3baa08', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.4B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 80,
 6,
 2600,
 866,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('2c37f846-0fc1-4ea2-8a11-7b2848e772be', 
 'Professional business with proven market demand and scalability.',
 'Market size $3.2B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1200,
 400,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('3bcc47e7-883e-48e2-96dc-ee41bad53e48', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.9B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 600,
 200,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('3c40063c-76cc-4453-a157-0e6d2ac7e65e', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.1B annually, growing 10%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1400,
 466,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('3d109c5a-0f71-4ac7-b558-2623e8d39f43', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.7B annually, growing 12%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 900,
 300,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('40bcd87e-329a-40b1-8dbc-6ea0ea188cba', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.8B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1500,
 500,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('45a827e1-e23f-42df-a2bd-4ccc8d969d13', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.1B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1800,
 600,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('47685a3c-5751-4d20-b573-fe10e871d88a', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.8B annually, growing 16%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 700,
 233,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('49196a21-2800-4caf-ba1e-0f7c729916b0', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.6B annually, growing 14%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 650,
 216,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('499b113c-2644-4125-8042-de8dfe1416e6', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.9B annually, growing 18%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1100,
 366,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('4b14e2a1-58e4-4616-bae8-a02ce570c16b', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.2B annually, growing 13%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 800,
 266,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('5460edd6-a4da-4a4a-9bd5-a352e24703a9', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.5B annually, growing 10%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1300,
 433,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('55426705-51b2-45af-bb20-7091d079408c', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.7B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1000,
 333,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('5be31407-a385-41a2-affa-1ae9fa635896', 
 'Professional business with proven market demand and scalability.',
 'Market size $8.2B annually, growing 8%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1800,
 600,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('60607a9d-cbc5-44b9-86bc-889f759d61ec', 
 'Professional business with proven market demand and scalability.',
 'Market size $5.6B annually, growing 10%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1500,
 500,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('642d0d71-16ef-46f5-9f3f-1cfc900df706', 
 'Professional business with proven market demand and scalability.',
 'Market size $6.8B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1700,
 566,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('6ca12608-3841-494d-b665-b90fe598c60d', 
 'Professional business with proven market demand and scalability.',
 'Market size $4.2B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1200,
 400,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('6e8f9a93-692a-4526-bed1-90c0d9351616', 
 'Professional business with proven market demand and scalability.',
 'Market size $3.9B annually, growing 12%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1400,
 466,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('7618517c-88a8-4949-8cbf-bcc091271abc', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.1B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 900,
 300,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('818a5bbc-20fb-449a-84d9-b69a513f85d4', 
 'Professional business with proven market demand and scalability.',
 'Market size $3.4B annually, growing 10%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1600,
 533,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('82c7afaf-4196-49e9-867e-4ec4ab5c7725', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.8B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1400,
 466,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('84d4df93-67e6-448c-8c01-6538b9dddad4', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.2B annually, growing 7%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 700,
 233,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('87be1a69-634d-40a8-9774-af25163f0af7', 
 'Professional business with proven market demand and scalability.',
 'Market size $0.8B annually, growing 8%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 76,
 4,
 800,
 266,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('8a9e4d8f-5e03-4e62-af5e-18f562b4ef5c', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.5B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1300,
 433,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('8d6ab119-3894-4e7a-8ba6-63edd170b135', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.5B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2000,
 666,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('92b3d355-5161-4743-8dc3-8c4d7de11bd5', 
 'Professional business with proven market demand and scalability.',
 'Market size $15.2B annually, growing 7%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 80,
 6,
 2500,
 833,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('a6c8089a-7d73-4217-adcb-23d50b39fec0', 
 'Professional business with proven market demand and scalability.',
 'Market size $8.9B annually, growing 9%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2000,
 666,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('aac5a928-00e4-42c6-a23f-ac92c685eb4f', 
 'Professional business with proven market demand and scalability.',
 'Market size $7.3B annually, growing 8%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1200,
 400,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10'),
('bd0b340e-20c0-42ea-a27a-019ae66ece78', 
 'Professional business with proven market demand and scalability.',
 'Market size $12.1B annually, growing 7%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2300,
 766,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('c0214bd7-f7a7-4a09-ab10-70e3a0cb73f1', 
 'Professional business with proven market demand and scalability.',
 'Market size $9.8B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2400,
 800,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('d0f00009-4562-4198-958d-9cb2b6b25984', 
 'Professional business with proven market demand and scalability.',
 'Market size $11.5B annually, growing 10%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 79,
 6,
 2200,
 733,
 'Break-even at month 6, positive cash flow by month 7, 3x ROI by month 12'),
('d72c0380-2d7a-4bdc-b24e-95a4e7d37790', 
 'Professional business with proven market demand and scalability.',
 'Market size $2.7B annually, growing 12%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 78,
 5,
 1800,
 600,
 'Break-even at month 5, positive cash flow by month 6, 3x ROI by month 11'),
('e3c0c28e-29c6-4404-99c2-eb03887f78c0', 
 'Professional business with proven market demand and scalability.',
 'Market size $1.4B annually, growing 11%',
 'Local customers, wholesale buyers, retailers, export markets',
 'Opportunity for differentiation through quality and direct relationships',
 'Quality products, strong customer service, direct market access, competitive pricing',
 'Direct sales (40%), Wholesale (35%), Export (25%)',
 'High scalability potential with proper execution',
 77,
 4,
 1400,
 466,
 'Break-even at month 4, positive cash flow by month 5, 3x ROI by month 10');