-- Rise Africa Skills: LAYER 2 - STARTUP TEMPLATES (All 46 Courses)
-- CORRECTED: Using table name 'startup_templates' (not seed_startup_templates)
-- =================================================================================

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('agro-forestry', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('bakery', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('honey-production', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('dairy-products', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('vegetable-farming', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('fish-farming', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('mushroom-farming', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('egg-production', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('poultry-farming', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('cassava-processing', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('spice-blending', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('juice-production', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('maize-milling', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('palm-oil-processing', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('jewelry', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('basket-weaving', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('pottery', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('tie-dye', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('leather-work', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('wood-carving', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('soap-making', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('candle-making', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('essential-oils', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('beadwork', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('textile-weaving', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('batik', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('appliance-repair', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('phone-repair', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('tailoring', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('hairdressing', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('beauty-services', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('cleaning-services', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('plumbing', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('electrical-work', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('shoe-repair', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('watch-repair', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('furniture-repair', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('motorcycle-repair', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('retail-shop', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('phone-reselling', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('market-stall', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('general-store', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('electronics-retail', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('clothing-retail', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('beverage-production', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

INSERT INTO startup_templates (course_id, week_1_plan, week_2_plan, week_3_plan, week_4_plan, critical_success_factors, common_mistakes, equipment_checklist, initial_investment_breakdown)
VALUES ('confectionery', '"[\"Market research\", \"Supplier identification\", \"Prototype creation\", \"Cost validation\", \"Competitor analysis\"]"'::jsonb, '"[\"Refine product\", \"Finalize suppliers\", \"Test packaging\", \"Calculate unit costs\", \"Plan marketing\"]"'::jsonb, '"[\"Setup operations\", \"Train team\", \"Create sales materials\", \"Build customer list\", \"Soft launch\"]"'::jsonb, '"[\"First customer feedback\", \"Refine quality\", \"Expand distribution\", \"Monitor cash flow\", \"Document processes\"]"'::jsonb, '"[\"Quality consistency\", \"Supplier reliability\", \"Customer relationships\", \"Cash flow management\", \"Team capability\"]"'::jsonb, '"[\"Insufficient market research\", \"Underpricing\", \"Poor quality control\", \"Neglecting cash flow\", \"Trying too much too soon\"]"'::jsonb, '"[\"Production equipment\", \"Packaging materials\", \"Quality control tools\", \"Record keeping system\", \"Storage facility\"]"'::jsonb, '"{\"equipment\": 800, \"materials\": 600, \"marketing\": 300, \"contingency\": 300}"'::jsonb);

COMMIT;
