-- Bakery Products - Bread & Pastries - Module 1, 20 real questions
-- Paste the WHOLE file, press Run. Safe to re-run.
ALTER TABLE quiz_questions ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE quizzes ALTER COLUMN id SET DEFAULT gen_random_uuid();

BEGIN;
DELETE FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1);
DELETE FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1;
INSERT INTO quizzes (id, course_id, title, description, passing_score, duration_minutes, quiz_category, difficulty_level, quiz_sequence)
VALUES (gen_random_uuid(), '3bcc47e7-883e-48e2-96dc-ee41bad53e48', 'Module 1 Assessment', 'Twenty questions on the fundamentals of Bakery Products - Bread & Pastries.', 70, 30, 'module', 'beginner', 1);
INSERT INTO quiz_questions (id, quiz_id, question_text, question_type, options, correct_answer, explanation, order_number)
VALUES
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'You are mixing water with active dry yeast to wake it up. Which water temperature range is correct?', 'multiple_choice', '{"A": "Cold tap water, about 10 °C (50 °F)", "B": "Warm water, about 40-46 °C (105-115 °F)", "C": "Very hot water, about 70 °C (158 °F)", "D": "Boiling water, 100 °C (212 °F)"}'::jsonb, 'B', 'Active dry yeast rehydrates best in water around 40-46 °C (105-115 °F) — warm to the wrist but not hot. Water above roughly 55-60 °C (130-140 °F) kills the yeast cells, and cold water simply leaves them sluggish.', 1),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'What is the FIRST thing a baker must do before touching dough, and again after handling money, raw eggs or the rubbish bin?', 'multiple_choice', '{"A": "Rinse the hands quickly under running water", "B": "Wipe the hands on a clean apron", "C": "Put gloves straight on over the hands", "D": "Wash hands with soap and clean water for at least 20 seconds, then dry them"}'::jsonb, 'D', 'Soap plus at least 20 seconds of scrubbing (including between fingers, thumbs and under nails) is what actually lifts grease and germs off skin; water alone or an apron wipe does not. Gloves over dirty hands just move the contamination onto the dough.', 2),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'In a bread recipe written in baker''s percentage, which ingredient is always set at 100%?', 'multiple_choice', '{"A": "The total flour", "B": "Water", "C": "The total dough weight", "D": "Yeast"}'::jsonb, 'A', 'In baker''s percentage the total flour is always 100%, and every other ingredient is expressed as a percentage of that flour weight. This lets you scale a recipe from 1 kg to 50 kg of flour without re-doing the whole calculation.', 3),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'Why is salt added to bread dough, apart from taste?', 'multiple_choice', '{"A": "It slows down yeast fermentation and strengthens the gluten", "B": "It makes the yeast work much faster", "C": "It replaces the need for sugar", "D": "It stops the bread from going mouldy for weeks"}'::jsonb, 'A', 'Salt tightens and strengthens the gluten network and slows yeast activity, giving a more controlled rise and better flavour development. Bread made with no salt rises fast, then collapses and tastes flat.', 4),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'A customer buys bread on Monday. To keep the loaf soft for the longest time at home, what should you tell them?', 'multiple_choice', '{"A": "Keep it in the refrigerator at about 4 °C (39 °F)", "B": "Leave it uncovered on the table so air can circulate", "C": "Keep it wrapped at room temperature, or freeze what will not be eaten within a day or two", "D": "Keep it in a sealed bag in direct sunlight"}'::jsonb, 'C', 'Bread goes stale fastest at refrigerator temperatures, because starch retrogradation (the staling reaction) is quickest just above freezing. Wrapped at room temperature is better, and freezing stops staling almost completely.', 5),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'Which flour is the correct choice for a chewy, well-risen loaf of bread?', 'multiple_choice', '{"A": "Cake or pastry flour, because it is very fine", "B": "Bread (strong) flour, because it has a higher protein content", "C": "Cassava or maize flour on its own", "D": "Self-raising flour, because it already contains a raising agent"}'::jsonb, 'B', 'Bread flour has more protein (roughly 11-13%), which forms the gluten network that traps gas and holds the loaf''s shape. Low-protein cake flour gives a crumbly, low-volume loaf, and gluten-free flours like cassava cannot form that network at all.', 6),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'How can you tell that a shaped loaf has proved enough and is ready for the oven?', 'multiple_choice', '{"A": "It has doubled in size and a light fingertip dent springs back slowly, leaving a slight mark", "B": "The dent from your finger springs back instantly and completely", "C": "The dough has collapsed and feels very soft and wet", "D": "Exactly 30 minutes have passed, whatever the weather"}'::jsonb, 'A', 'The poke test is more reliable than the clock: a slow, partial spring-back means the gluten is relaxed and the dough is full of gas but still has strength left for oven spring. Instant spring-back means under-proved; no spring-back at all means over-proved.', 7),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'In your bakery, where should raw eggs be stored in a shared refrigerator?', 'multiple_choice', '{"A": "On the top shelf, above the cream and finished cakes", "B": "On a lower shelf, below and separate from ready-to-eat foods, in their own covered container", "C": "Loose in the door next to the icing", "D": "Anywhere, as long as the fridge is cold"}'::jsonb, 'B', 'Raw eggs can carry Salmonella on the shell, so they go below ready-to-eat items so nothing can drip or shed onto food that will not be cooked again. Keeping them in a covered container also stops shell debris contaminating other foods.', 8),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'You knead a lean bread dough and want to check that the gluten is developed. What does the ''windowpane test'' show?', 'multiple_choice', '{"A": "The dough tears immediately when stretched, showing it is ready", "B": "The dough floats in a bowl of water", "C": "The dough sticks to your hands, showing it is ready", "D": "A small piece can be stretched thin enough to see light through it without tearing"}'::jsonb, 'D', 'When gluten strands are properly developed and aligned, a small piece of dough stretches into a thin translucent membrane before tearing. If it tears straight away, it needs more kneading or more rest.', 9),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'Your shortcrust pastry comes out tough and hard instead of short and crumbly. What is the most likely cause?', 'multiple_choice', '{"A": "Too little sugar in the mix", "B": "The oven was too hot", "C": "Too much water and over-working the dough, which develops gluten", "D": "The fat was too cold"}'::jsonb, 'C', 'Shortcrust depends on fat coating the flour so gluten stays undeveloped; excess water plus heavy handling builds gluten strands and makes the pastry tough and shrunken. Use minimal cold water and mix only until it just comes together.', 10),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'Bread and pastries containing fresh cream or custard are left out on a display table. Between which temperatures do bacteria multiply most rapidly — the ''danger zone''?', 'multiple_choice', '{"A": "Between -18 °C and 0 °C (0 °F and 32 °F)", "B": "Between 5 °C and 60 °C (41 °F and 140 °F)", "C": "Between 60 °C and 100 °C (140 °F and 212 °F)", "D": "Only above 70 °C (158 °F)"}'::jsonb, 'B', 'Roughly 5-60 °C (41-140 °F) is the range where food-poisoning bacteria grow fastest, so cream- and custard-filled items must be kept chilled below 5 °C (41 °F) and not left on an unrefrigerated table for hours. Plain baked bread is low-risk, but dairy fillings are not.', 11),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'A loaf comes out of the oven with a big ragged tear or burst along one side. What most likely went wrong?', 'multiple_choice', '{"A": "The dough was over-proved", "B": "The oven was too cool", "C": "There was too much salt", "D": "The dough was under-proved or not scored, so the gas forced its way out at the weakest point"}'::jsonb, 'D', 'During oven spring the gas expands sharply; if the dough is under-proved or has no deliberate cut, it bursts at whatever point is weakest, usually the side seam. Scoring the top gives the expansion a planned place to go.', 12),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'How can you check that a plain, lean loaf is fully baked inside rather than guessing by colour?', 'multiple_choice', '{"A": "The crust is dark brown, which always means it is done", "B": "The centre reaches about 60 °C (140 °F)", "C": "The centre reaches about 93-96 °C (200-205 °F) and the base sounds hollow when tapped", "D": "It has been in the oven for exactly 25 minutes"}'::jsonb, 'C', 'A lean bread''s starch is fully gelatinised and its crumb set at roughly 93-96 °C (200-205 °F) in the centre; enriched, sweeter doughs are usually pulled a little lower, around 88-90 °C (190-195 °F). Crust colour can be dark while the middle is still raw and gummy.', 13),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'You must slice and pack bread after handling raw meat pies. What is the correct practice to avoid cross-contamination?', 'multiple_choice', '{"A": "Wipe the same board with a dry cloth and continue", "B": "Use the same knife but turn it over to the other side", "C": "Wash hands, and use a separate clean board and knife for the ready-to-eat bread", "D": "Slice the bread first thing in the morning and leave it uncovered all day"}'::jsonb, 'C', 'Raw meat juices carry bacteria that will not be cooked away once transferred to baked bread, so separate clean equipment plus handwashing between tasks is the only safe method. A dry wipe just spreads the contamination around the board.', 14),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'Your bread is dense with a tight crumb and very little rise, even though the yeast was fresh. Which cause is most likely?', 'multiple_choice', '{"A": "The dough was proved in a place that was too cold, or was under-kneaded and under-proved", "B": "Too much yeast was used", "C": "The oven was too hot", "D": "Too much water was used"}'::jsonb, 'A', 'Yeast works slowly below about 20 °C (68 °F), and an under-kneaded dough cannot hold the gas it does produce, so both give a heavy, tight loaf. Prove in a warm, draught-free spot around 25-28 °C (77-82 °F) and judge by the dough''s size, not the clock.', 15),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'You are costing your bread to set a selling price. Which is the correct basis for that price?', 'multiple_choice', '{"A": "Ingredient cost per loaf only", "B": "Whatever the neighbouring shop charges, regardless of your own costs", "C": "Ingredient cost per loaf doubled, with no other costs counted", "D": "Total cost per loaf — ingredients, fuel or gas, packaging, transport and a value for your labour — plus a profit margin"}'::jsonb, 'D', 'Ingredients are often only part of what a loaf really costs you; fuel, packaging, transport and your own time must all be recovered before any profit exists. Pricing on ingredients alone is the most common reason a cottage bakery works hard and still loses money.', 16),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'A batch of dough over-proved badly while you were away. What is the best practical action?', 'multiple_choice', '{"A": "Bake it immediately as it is and sell it as normal bread", "B": "Knock it back, reshape it and give it a short second prove, accepting a slightly weaker loaf", "C": "Add more yeast and mix again", "D": "Put it in the freezer for an hour, then bake without reshaping"}'::jsonb, 'B', 'Degassing and reshaping redistributes the gas and gives the weakened gluten one more chance to hold structure, which usually rescues the batch. Baking it as it is gives a collapsed, coarse-holed loaf with a sour smell, and more yeast only speeds up a problem caused by too much fermentation.', 17),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'When making laminated pastry such as puff or croissants, why must the dough and butter be kept cool while rolling?', 'multiple_choice', '{"A": "Cool butter tastes better than warm butter", "B": "It stops the yeast from dying", "C": "Cold dough absorbs less water", "D": "Cool butter stays as separate solid layers; if it melts into the dough the layers merge and the pastry will not rise into flakes"}'::jsonb, 'D', 'Lamination works because distinct sheets of solid fat separate sheets of dough; in the oven the water in that fat and dough turns to steam and pushes the layers apart. Once butter melts and is absorbed into the dough, there are no layers left to lift.', 18),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'You want to increase the profit on a loaf you already sell at a fixed price customers accept. Which action genuinely improves margin without cheating the customer?', 'multiple_choice', '{"A": "Reduce the salt in the recipe to save money", "B": "Buy flour in larger bulk quantities and bake full oven loads to cut cost per loaf and fuel per loaf", "C": "Bake the loaf for less time so it uses less gas", "D": "Reduce the flour weight per loaf while keeping the same price and packaging"}'::jsonb, 'B', 'Bulk purchasing lowers your unit ingredient cost, and filling the oven spreads the same fuel cost over more loaves — both raise margin while the product stays the same. Under-baking or quietly shrinking the loaf damages quality and customer trust, which costs more than it saves.', 19),
(gen_random_uuid(), (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1), 'You have no scale marked in baker''s percentage and want 2% salt on a dough made with 3 kg (6.6 lb) of flour. How much salt do you weigh out?', 'multiple_choice', '{"A": "20 g (0.7 oz)", "B": "150 g (5.3 oz)", "C": "60 g (2.1 oz)", "D": "600 g (21 oz)"}'::jsonb, 'C', 'Baker''s percentages are taken on flour weight, so 2% of 3000 g is 60 g (about 2.1 oz). Getting this arithmetic right matters commercially: a tenfold error in salt either ruins the flavour or halts fermentation entirely.', 20);
COMMIT;

SELECT COUNT(*) AS questions_loaded FROM quiz_questions
WHERE quiz_id = (SELECT id FROM quizzes WHERE course_id='3bcc47e7-883e-48e2-96dc-ee41bad53e48' AND quiz_sequence=1);
-- expect 20
