INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('64e43c02-a817-42ce-8877-5929e5c76a52', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('84d4df93-67e6-448c-8c01-6538b9dddad4', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('3bcc47e7-883e-48e2-96dc-ee41bad53e48', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('c8611d21-206f-4451-bed4-06deb144b006', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('962d0ef0-e152-4b89-8a21-df55c594243d', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('a6c8089a-7d73-4217-adcb-23d50b39fec0', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('97331b53-bb8f-4169-a904-9e1fcc43e596', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('87be1a69-634d-40a8-9774-af25163f0af7', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('1a031389-d8f8-4a3d-9299-d93f96e7d0a4', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('9dfcde1b-5589-4d5e-9180-d205d4468a49', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('dcaaf6df-9253-48e2-aa27-8ffb426e9992', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('a2304fb7-220a-4162-a8ab-e91d995d0593', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('d72c0380-2d7a-4bdc-b24e-95a4e7d37790', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('d44d4c27-5f16-4d58-8458-f21c17f1ae62', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('57bb0d45-5e6e-4f76-b285-0c8153f8a812', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('1551f95c-f7f3-478b-9a5c-f888eec9ed51', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('e89cf036-129a-43bd-bff5-8c96b20fee87', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('d47d2e6a-e5d4-45f6-8059-9e84cca1f189', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('f90335b0-bf8f-4a31-a610-9d6220edfd34', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('c7fc7116-7e0a-4a8d-89a0-1d9748c3e429', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('642d0d71-16ef-46f5-9f3f-1cfc900df706', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('14b6d99a-a809-4cbf-9b50-407dbfb0cecf', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('5d04f957-1d55-49fc-b8eb-a621aa1b309a', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('c0214bd7-f7a7-4a09-ab10-70e3a0cb73f1', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('aac5a928-00e4-42c6-a23f-ac92c685eb4f', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('60607a9d-cbc5-44b9-86bc-889f759d61ec', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('82c7afaf-4196-49e9-867e-4ec4ab5c7725', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('40bcd87e-329a-40b1-8dbc-6ea0ea188cba', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('0c48f1de-6fe4-4870-965d-815a9a430a8f', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('da063670-96e1-4ac4-9ef4-f5a6c6bcc166', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('1dbb8ef3-e7c6-47c2-9bb4-9caf6e9594de', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('8d6ab119-3894-4e7a-8ba6-63edd170b135', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('e97ee07a-2902-42b9-8aae-d48efa28287b', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('274046b3-d052-4203-af77-f58052048061', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('bc0d527a-bf09-4f39-a902-36b57e1a3afe', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('6ca12608-3841-494d-b665-b90fe598c60d', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('669364ca-73c5-4273-ac35-aff218f2ffde', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('9803a0f3-e9f6-4cf9-8a86-7c44433822ca', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('8fbd9e92-242b-4dd6-9029-1cff0e24adfb', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('5460edd6-a4da-4a4a-9bd5-a352e24703a9', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('956b52bf-a202-4248-bf45-d2b6058a4a39', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('cd8315cc-73d5-4192-bc9d-7bfa59a2d138', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('818a5bbc-20fb-449a-84d9-b69a513f85d4', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('dd169961-8e43-40dc-81d7-64fc5a0bbe39', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('c9d6672b-1adc-47c1-8d9b-649e6816f336', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
INSERT INTO startup_templates (course_id, initial_investment_breakdown, equipment_checklist, material_sourcing_guide, week_by_week_timeline, critical_success_factors, common_mistakes, supplier_contacts)
VALUES ('90c0b430-fe20-4ff3-853c-3a411f657f95', '{"equipment":800,"materials":600}'::jsonb, '{"tools":"equipment"}'::jsonb, '{"type":"local"}'::jsonb, '{"week1":"research"}'::jsonb, '{"factor1":"quality"}'::jsonb, '{"mistake1":"underpricing"}'::jsonb, '{"phone":"254700000000"}'::jsonb);
COMMIT;
